// 管理画面（/admin）。公開サイトのデザインとは切り離した、シンプルな監視・編集用ダッシュボード。
// ページ自体は誰でも開けるが、中身のデータは ADMIN_TOKEN を知っている人だけが
// 各種 /api/admin/* を叩けるため閲覧・編集できる。
// トークンはブラウザのlocalStorageにのみ保存され、サーバー側には保存しない。

import {
  CITY_STATUS_LABEL,
  CITY_STATUSES,
  FACILITY_KIND_LABEL,
  FACILITY_KINDS,
  GENDER_LABEL,
  GENDER_OPTIONS,
  NEWS_CATEGORIES,
  ORG_KIND_LABEL,
  ORG_KINDS,
  ORG_STATUS_LABEL,
  ORG_STATUSES,
  PERSON_STATUS_LABEL,
  PERSON_STATUSES,
  RELATION_TYPE_LABEL,
  RELATION_TYPES,
  WEATHER_CONDITIONS,
} from "../constants";

export function adminDashboardPage(): string {
  const constantsScript =
    "window.__NEWS_CATEGORIES__ = " + JSON.stringify(NEWS_CATEGORIES) + ";\n" +
    "window.__PERSON_STATUSES__ = " + JSON.stringify(PERSON_STATUSES) + ";\n" +
    "window.__PERSON_STATUS_LABEL__ = " + JSON.stringify(PERSON_STATUS_LABEL) + ";\n" +
    "window.__ORG_STATUSES__ = " + JSON.stringify(ORG_STATUSES) + ";\n" +
    "window.__ORG_STATUS_LABEL__ = " + JSON.stringify(ORG_STATUS_LABEL) + ";\n" +
    "window.__ORG_KINDS__ = " + JSON.stringify(ORG_KINDS) + ";\n" +
    "window.__ORG_KIND_LABEL__ = " + JSON.stringify(ORG_KIND_LABEL) + ";\n" +
    "window.__CITY_STATUSES__ = " + JSON.stringify(CITY_STATUSES) + ";\n" +
    "window.__CITY_STATUS_LABEL__ = " + JSON.stringify(CITY_STATUS_LABEL) + ";\n" +
    "window.__FACILITY_KINDS__ = " + JSON.stringify(FACILITY_KINDS) + ";\n" +
    "window.__FACILITY_KIND_LABEL__ = " + JSON.stringify(FACILITY_KIND_LABEL) + ";\n" +
    "window.__GENDER_OPTIONS__ = " + JSON.stringify(GENDER_OPTIONS) + ";\n" +
    "window.__GENDER_LABEL__ = " + JSON.stringify(GENDER_LABEL) + ";\n" +
    "window.__WEATHER_CONDITIONS__ = " + JSON.stringify(WEATHER_CONDITIONS) + ";\n" +
    "window.__RELATION_TYPES__ = " + JSON.stringify(RELATION_TYPES) + ";\n" +
    "window.__RELATION_TYPE_LABEL__ = " + JSON.stringify(RELATION_TYPE_LABEL) + ";\n";

  return (
    "<!doctype html>\n" +
    '<html lang="ja">\n' +
    "<head>\n" +
    '<meta charset="utf-8" />\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1" />\n' +
    "<title>管理画面 | モーゼン・クロニクル</title>\n" +
    '<meta name="robots" content="noindex" />\n' +
    "<style>\n" +
    STYLE +
    "\n</style>\n" +
    "</head>\n" +
    "<body>\n" +
    HTML_BODY +
    "\n<script>\n" +
    constantsScript +
    SCRIPT +
    "\n</script>\n" +
    "</body>\n" +
    "</html>\n"
  );
}

const STYLE = [
  ":root { color-scheme: light dark; --bg:#0f1115; --panel:#1a1d24; --line:#2a2e38; --ink:#e8e8ea; --soft:#9a9fac; --accent:#5b8cff; --ok:#3ecf8e; --bad:#ff5d5d; --warn:#ffb84d; }",
  "* { box-sizing: border-box; }",
  "body { margin:0; background:var(--bg); color:var(--ink); font-family:'Hiragino Sans','Noto Sans JP',sans-serif; }",
  ".wrap { max-width: 960px; margin: 0 auto; padding: 1.5rem 1.2rem 4rem; }",
  "h1 { font-size: 1.3rem; margin: 0 0 0.2rem; }",
  ".sub { color: var(--soft); font-size: 0.8rem; margin-bottom: 1.4rem; }",
  ".panel { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 1rem 1.1rem; margin-bottom: 1rem; }",
  ".row { display:flex; gap:0.8rem; flex-wrap:wrap; align-items:center; }",
  "input[type=password], input[type=text] { background:#0c0e12; border:1px solid var(--line); color:var(--ink); padding:0.5rem 0.7rem; border-radius:6px; font-size:0.9rem; flex:1; min-width:200px; }",
  "button { background: var(--accent); color:#fff; border:none; padding:0.55rem 1rem; border-radius:6px; font-size:0.85rem; cursor:pointer; }",
  "button.secondary { background:#2a2e38; }",
  "button:disabled { opacity:0.5; cursor:default; }",
  ".stat-grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(160px,1fr)); gap:0.8rem; }",
  ".stat { background:#0c0e12; border:1px solid var(--line); border-radius:6px; padding:0.7rem 0.8rem; }",
  ".stat .label { font-size:0.72rem; color:var(--soft); }",
  ".stat .value { font-size:1.15rem; margin-top:0.15rem; }",
  "table { width:100%; border-collapse:collapse; font-size:0.82rem; }",
  "th, td { text-align:left; padding:0.4rem 0.5rem; border-bottom:1px solid var(--line); }",
  "th { color:var(--soft); font-weight:600; }",
  ".badge { display:inline-block; padding:0.1rem 0.5rem; border-radius:999px; font-size:0.72rem; }",
  ".badge.success { background:rgba(62,207,142,0.15); color:var(--ok); }",
  ".badge.failed { background:rgba(255,93,93,0.15); color:var(--bad); }",
  ".badge.running { background:rgba(255,184,77,0.15); color:var(--warn); }",
  ".hidden { display:none; }",
  "#loginError, #actionMsg { font-size:0.82rem; margin-top:0.5rem; }",
  "#loginError { color: var(--bad); }",
  "#actionMsg { color: var(--soft); }",
  ".error-text { color: var(--bad); font-family: monospace; font-size:0.78rem; }",
  "a { color: var(--accent); }",
  "h3 { margin-top:0; }",
  "textarea, select, input[type=number] {",
  "  background:#0c0e12; border:1px solid var(--line); color:var(--ink); padding:0.5rem 0.7rem; border-radius:6px; font-size:0.85rem;",
  "  font-family:inherit; width:100%; box-sizing:border-box;",
  "}",
  "textarea { min-height:8em; resize:vertical; }",
  ".field { margin-bottom:0.7rem; }",
  ".field label { display:block; font-size:0.75rem; color:var(--soft); margin-bottom:0.25rem; }",
  ".field-row { display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:0.7rem; }",
  "tr.clickable { cursor:pointer; }",
  "tr.clickable:hover { background:#0c0e12; }",
  ".editor { border-top:1px solid var(--line); margin-top:0.8rem; padding-top:0.8rem; }",
  ".editor.hidden { display:none; }",
  ".time-chip { display:inline-flex; align-items:center; gap:0.3rem; background:#0c0e12; border:1px solid var(--line); border-radius:6px; padding:0.3rem 0.5rem; }",
  ".time-chip input { background:transparent; border:none; color:var(--ink); width:5.5em; font-size:0.85rem; }",
  ".time-chip button { padding:0 0.4rem; background:transparent; color:var(--bad); font-size:0.9rem; }",
  ".tabs { display:flex; gap:0.4rem; flex-wrap:wrap; margin-bottom:1rem; }",
  ".tab-btn { background:#0c0e12; border:1px solid var(--line); color:var(--soft); padding:0.5rem 0.9rem; border-radius:6px 6px 0 0; }",
  ".tab-btn.active { background:var(--panel); color:var(--ink); border-bottom-color:var(--panel); font-weight:700; }",
  ".tab-panel { display:none; }",
  ".tab-panel.active { display:block; }",
  ".org-detail { font-size:0.72rem; color:var(--soft); margin-top:0.15rem; }",
  ".chip-row { display:flex; flex-wrap:wrap; gap:0.5rem; }",
  ".chip { display:inline-flex; align-items:center; gap:0.3rem; background:#0c0e12; border:1px solid var(--line); border-radius:999px; padding:0.3rem 0.4rem 0.3rem 0.75rem; font-size:0.82rem; line-height:1.4; }",
  ".chip button { background:transparent; border:none; color:var(--soft); font-size:0.8rem; line-height:1; padding:0.3rem 0.45rem; cursor:pointer; border-radius:999px; }",
  ".chip button:hover { background:#2a2e38; color:var(--ink); }",
].join("\n");

const HTML_BODY = [
  '<div class="wrap">',
  "<h1>モーゼン・クロニクル 管理画面</h1>",
  '<div class="sub">世界の進行状況を監視し、ニュース・人物・経済を編集できます。</div>',

  '<div class="panel" id="loginPanel">',
  '<div class="row">',
  '<input type="password" id="tokenInput" placeholder="ADMIN_TOKEN を入力" autocomplete="off" />',
  '<button onclick="saveToken()">接続</button>',
  "</div>",
  '<div id="loginError"></div>',
  "</div>",

  '<div id="dashboard" class="hidden">',

  '<div class="tabs">',
  '<button class="tab-btn active" data-tab="overview" onclick="showTab(\'overview\')">概要</button>',
  '<button class="tab-btn" data-tab="news" onclick="showTab(\'news\')">ニュース</button>',
  '<button class="tab-btn" data-tab="people" onclick="showTab(\'people\')">人物</button>',
  '<button class="tab-btn" data-tab="economy" onclick="showTab(\'economy\')">経済</button>',
  '<button class="tab-btn" data-tab="cities" onclick="showTab(\'cities\')">都市</button>',
  '<button class="tab-btn" data-tab="settings" onclick="showTab(\'settings\')">設定</button>',
  "</div>",

  // --- 概要タブ ---
  '<div class="tab-panel active" data-tab-panel="overview">',
  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  '<div class="row">',
  '<button onclick="runSimulation()" id="simulateBtn">今すぐニュースを生成</button>',
  '<button class="secondary" onclick="refresh()">今すぐ更新</button>',
  '<button class="secondary" onclick="logout()">ログアウト</button>',
  "</div>",
  '<div class="sub" id="lastUpdated" style="margin:0">-</div>',
  "</div>",
  '<div id="actionMsg"></div>',
  "</div>",
  '<div class="panel"><div class="stat-grid" id="statGrid"></div></div>',
  '<div class="panel">',
  "<h3>直近の実行履歴</h3>",
  '<table><thead><tr><th>世界日</th><th>状態</th><th>AI呼び出し</th><th>開始</th><th>エラー</th></tr></thead><tbody id="runsBody"></tbody></table>',
  "</div>",
  '<div class="panel"><h3>最新ニュース</h3><div id="newsList" class="sub">-</div></div>',
  "</div>",

  // --- ニュースタブ ---
  '<div class="tab-panel" data-tab-panel="news">',
  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  "<h3 style=\"margin:0\">ニュース管理</h3>",
  '<button onclick="showNewsCreateForm()">+ ニュースを作成</button>',
  "</div>",
  '<table style="margin-top:0.6rem"><thead><tr><th>タイトル</th><th>タグ</th><th>掲載</th></tr></thead><tbody id="newsAdminBody"></tbody></table>',
  '<div id="newsEditor" class="editor hidden">',
  '<div class="field"><label>タイトル</label><input type="text" id="newsEditTitle" /></div>',
  '<div class="field"><label>タグ</label><select id="newsEditCategory"></select></div>',
  '<div class="field"><label>本文</label><textarea id="newsEditBody"></textarea></div>',
  '<div class="field">',
  "<label>担当記者（任意・職業が「記者」の人物から検索）</label>",
  '<input type="text" id="newsEditReporterSearch" placeholder="名前で検索（空欄で記者一覧を表示）" oninput="searchNewsEditReporterCandidates()" onfocus="searchNewsEditReporterCandidates()" />',
  '<div id="newsEditReporterResults" class="sub" style="max-height:8em; overflow-y:auto; margin-top:0.3rem"></div>',
  '<div class="row"><span class="sub" id="newsEditReporterSelected">（未指定）</span><button type="button" class="secondary" onclick="clearNewsEditReporter()">解除</button></div>',
  "</div>",
  '<div class="row"><button onclick="saveNews()">保存</button><button class="secondary" onclick="deleteNewsItem()" style="background:var(--bad)">削除</button><button class="secondary" onclick="closeNewsEditor()">閉じる</button></div>',
  '<div id="newsEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",

  '<div class="panel editor hidden" id="newsCreator">',
  "<h3>ニュースを作成</h3>",
  '<div class="field" style="max-width:360px">',
  "<label>作成方法</label>",
  '<select id="newsCreateMode" onchange="onNewsCreateModeChange()">',
  '<option value="ai">AIに依頼（人物・ジャンル・キーワード・企業を指定可）</option>',
  '<option value="manual">完全手動で入力</option>',
  "</select>",
  "</div>",

  '<div class="field">',
  "<label>関連する人物（複数選択可・任意）</label>",
  '<input type="text" id="newsCreatePeopleSearch" placeholder="名前で検索して追加" oninput="searchNewsCreatePeople()" />',
  '<div id="newsCreatePeopleResults" class="sub" style="max-height:8em; overflow-y:auto; margin-top:0.3rem"></div>',
  '<div id="newsCreatePeopleSelected" class="row" style="margin-top:0.4rem"></div>',
  "</div>",
  '<div class="field">',
  "<label>関連する組織（複数選択可・任意）</label>",
  '<div id="newsCreateOrgChecklist" class="row"></div>',
  "</div>",
  '<div class="field">',
  "<label>担当記者（任意・未指定ならその都市の記者からランダムに自動割り当て）</label>",
  '<input type="text" id="newsCreateReporterSearch" placeholder="名前で検索（空欄で記者一覧を表示）" oninput="searchNewsCreateReporterCandidates()" onfocus="searchNewsCreateReporterCandidates()" />',
  '<div id="newsCreateReporterResults" class="sub" style="max-height:8em; overflow-y:auto; margin-top:0.3rem"></div>',
  '<div class="row"><span class="sub" id="newsCreateReporterSelected">（未指定・自動で割り当てられます）</span><button type="button" class="secondary" onclick="clearNewsCreateReporter()">解除</button></div>',
  "</div>",

  '<div id="newsCreateAiFields">',
  '<div class="field-row">',
  '<div class="field"><label>ジャンル指定（任意）</label><select id="newsCreateGenre"></select></div>',
  '<div class="field"><label>キーワード（任意）</label><input type="text" id="newsCreateKeywords" placeholder="例: 台風, 停電" /></div>',
  "</div>",
  '<div class="sub">これらは空でもそのままAIに送信され、通常どおり自律的に出来事が生成されます。</div>',
  "</div>",

  '<div id="newsCreateManualFields" class="hidden">',
  '<div class="field"><label>タイトル</label><input type="text" id="newsCreateTitle" /></div>',
  '<div class="field"><label>ジャンル</label><select id="newsCreateCategory"></select></div>',
  '<div class="field"><label>本文</label><textarea id="newsCreateBody"></textarea></div>',
  '<div class="field">',
  "<label>状態変化（任意・人物や組織、経済を実際に変更したい場合）</label>",
  '<div id="stateChangeRows"></div>',
  '<button type="button" class="secondary" onclick="addStateChangeRow()">+ 状態変化を追加</button>',
  "</div>",
  "</div>",

  '<div class="row"><button onclick="submitNewsCreate()">作成</button><button class="secondary" onclick="closeNewsCreator()">閉じる</button></div>',
  '<div id="newsCreateMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",

  // --- 人物タブ ---
  '<div class="tab-panel" data-tab-panel="people">',
  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  "<h3 style=\"margin:0\">職業タイプ管理</h3>",
  '<button class="secondary" onclick="toggleOccupationTypesPanel()">表示/非表示</button>',
  "</div>",
  '<div id="occupationTypesPanel" class="hidden" style="margin-top:0.6rem">',
  '<div class="row"><input type="text" id="newOccupationTypeName" placeholder="新しい職業名" /><button onclick="addOccupationType()">追加</button></div>',
  '<div id="occupationTypesList" class="chip-row" style="margin-top:0.6rem"></div>',
  '<div id="occupationTypesMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",

  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  "<h3 style=\"margin:0\">人物管理</h3>",
  '<button onclick="showPersonCreateForm()">+ 人物を追加</button>',
  "</div>",
  '<div class="field-row" style="margin-top:0.6rem">',
  '<div class="field"><label>名前で検索</label><input type="text" id="peopleSearchAdmin" placeholder="名前で検索" oninput="searchPeopleAdmin()" /></div>',
  '<div class="field"><label>職業で絞込</label><select id="peopleFilterOccupation" onchange="searchPeopleAdmin()"></select></div>',
  '<div class="field"><label>状態で絞込</label><select id="peopleFilterStatus" onchange="searchPeopleAdmin()"></select></div>',
  "</div>",
  '<div id="peopleAdminCount" class="sub"></div>',
  '<table style="margin-top:0.4rem"><thead><tr><th>名前</th><th>職業</th><th>状態</th></tr></thead><tbody id="peopleAdminBody"></tbody></table>',
  '<div id="personEditor" class="editor hidden">',
  '<div class="field-row">',
  '<div class="field"><label>名前</label><input type="text" id="personEditName" /></div>',
  '<div class="field"><label>ふりがな</label><input type="text" id="personEditKana" /></div>',
  '<div class="field"><label>年齢</label><input type="number" id="personEditAge" /></div>',
  '<div class="field"><label>性別</label><select id="personEditGender"></select></div>',
  '<div class="field"><label>職業</label><select id="personEditOccupation"></select></div>',
  '<div class="field"><label>役職</label><input type="text" id="personEditJobTitle" placeholder="例: 課長、代表取締役" /></div>',
  '<div class="field"><label>所属組織（就職先）</label><select id="personEditOrg"></select></div>',
  '<div class="field" id="personEditCityField"><label>所在都市</label><select id="personEditCity"></select></div>',
  '<div class="field"><label>年収</label><input type="number" id="personEditIncome" placeholder="円" /></div>',
  '<div class="field"><label>所持金</label><input type="number" id="personEditMoney" /></div>',
  '<div class="field"><label>生年月日</label><input type="text" id="personEditBirthDate" placeholder="YYYY-MM-DD（世界暦）" /></div>',
  '<div class="field"><label>生まれ</label><input type="text" id="personEditBirthplace" placeholder="例: ダイナン市" /></div>',
  '<div class="field"><label>状態</label><select id="personEditStatus"></select></div>',
  "</div>",
  '<div class="field"><label>プロフィール</label><textarea id="personEditBio" style="min-height:4em"></textarea></div>',
  '<div class="row"><button onclick="savePerson()">保存</button><button class="secondary" onclick="closePersonEditor()">閉じる</button></div>',
  '<div id="personEditMsg" class="sub" style="margin-top:0.4rem"></div>',

  '<div id="personRelSection" class="hidden" style="margin-top:1rem;border-top:1px solid var(--line);padding-top:0.8rem">',
  "<h3 style=\"font-size:0.95rem\">人間関係・家系図</h3>",
  '<table><thead><tr><th>相手</th><th>関係</th><th></th></tr></thead><tbody id="personRelBody"></tbody></table>',
  '<div class="field-row" style="margin-top:0.6rem">',
  '<div class="field">',
  "<label>相手を検索して追加</label>",
  '<input type="text" id="personRelSearch" placeholder="名前で検索" oninput="searchPersonRelCandidates()" />',
  '<div id="personRelSearchResults" class="sub" style="max-height:8em; overflow-y:auto; margin-top:0.3rem"></div>',
  "</div>",
  '<div class="field"><label>関係の種類</label><select id="personRelType"></select></div>',
  "</div>",
  '<div class="sub" id="personRelSelected">（相手を検索結果から選択してください）</div>',
  '<div class="row" style="margin-top:0.4rem"><button class="secondary" onclick="addPersonRelationship()">この関係を追加</button></div>',
  '<div id="personRelMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",

  '<div id="personChildbirthSection" class="hidden" style="margin-top:1rem;border-top:1px solid var(--line);padding-top:0.8rem">',
  "<h3 style=\"font-size:0.95rem\">出産を記録</h3>",
  '<div class="sub">この人物を母親として、新しい人物を作成し親子関係（既存の子がいれば兄弟姉妹関係も）を結びます。</div>',
  '<div class="field-row" style="margin-top:0.4rem">',
  '<div class="field"><label>子の名前</label><input type="text" id="childbirthName" /></div>',
  '<div class="field"><label>子のふりがな</label><input type="text" id="childbirthKana" /></div>',
  '<div class="field"><label>子の性別</label><select id="childbirthGender"></select></div>',
  "</div>",
  '<div class="field">',
  "<label>父親（任意・検索して選択）</label>",
  '<input type="text" id="childbirthFatherSearch" placeholder="名前で検索" oninput="searchChildbirthFatherCandidates()" />',
  '<div id="childbirthFatherResults" class="sub" style="max-height:8em; overflow-y:auto; margin-top:0.3rem"></div>',
  '<div class="sub" id="childbirthFatherSelected">（未指定）</div>',
  "</div>",
  '<div class="row"><button class="secondary" onclick="submitChildbirth()">出産を記録</button></div>',
  '<div id="childbirthMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",
  "</div>",
  "</div>",

  // --- 経済タブ ---
  '<div class="tab-panel" data-tab-panel="economy">',
  '<div class="panel">',
  '<div class="field" style="max-width:320px">',
  "<label>物価指数</label>",
  '<div class="row"><input type="number" id="priceIndexInput" step="0.1" /><button onclick="savePriceIndex()">更新</button></div>',
  "</div>",
  '<div id="econMsg" class="sub"></div>',
  "</div>",

  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  "<h3 style=\"margin:0\">企業・組織一覧</h3>",
  '<button onclick="showOrgCreateForm()">+ 新しい企業を追加</button>',
  "</div>",
  '<table style="margin-top:0.6rem"><thead><tr><th>企業</th><th>種別</th><th>状態</th><th>株価</th><th></th></tr></thead><tbody id="econAdminBody"></tbody></table>',
  "</div>",

  '<div class="panel editor hidden" id="orgEditor">',
  '<h3 id="orgEditorTitle">企業を編集</h3>',
  '<div class="field-row">',
  '<div class="field"><label>名前</label><input type="text" id="orgEditName" /></div>',
  '<div class="field"><label>種別</label><select id="orgEditKind"></select></div>',
  '<div class="field" id="orgEditCityField"><label>所在都市</label><select id="orgEditCity"></select></div>',
  '<div class="field"><label>業種</label><input type="text" id="orgEditIndustry" placeholder="例: 製造業、IT、物流" /></div>',
  '<div class="field"><label>規模</label><input type="text" id="orgEditEmployeeScale" placeholder="例: 数十人、数百人" /></div>',
  '<div class="field"><label>創業年</label><input type="number" id="orgEditFoundedYear" /></div>',
  '<div class="field"><label>状態</label><select id="orgEditStatus"></select></div>',
  "</div>",
  '<div class="field"><label>説明</label><textarea id="orgEditDescription" style="min-height:4em"></textarea></div>',
  '<div class="row"><button onclick="saveOrg()">保存</button><button class="secondary" onclick="closeOrgEditor()">閉じる</button></div>',
  '<div id="orgEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",

  // --- 都市タブ ---
  '<div class="tab-panel" data-tab-panel="cities">',
  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  '<h3 style="margin:0">都市一覧</h3>',
  '<button onclick="showCityCreateForm()">+ 新しい都市を追加</button>',
  "</div>",
  '<div class="sub">Activeにした都市は、以後のニュース生成でランダムに舞台として選ばれるようになります。地図にも自動的に追加されます。</div>',
  '<table style="margin-top:0.6rem"><thead><tr><th>都市名</th><th>状態</th><th>人口</th><th></th></tr></thead><tbody id="citiesAdminBody"></tbody></table>',
  "</div>",

  '<div class="panel editor hidden" id="cityEditor">',
  '<h3 id="cityEditorTitle">都市を編集</h3>',
  '<div class="field-row">',
  '<div class="field"><label>都市名</label><input type="text" id="cityEditName" /></div>',
  '<div class="field"><label>人口</label><input type="number" id="cityEditPopulation" /></div>',
  '<div class="field"><label>状態</label><select id="cityEditStatus"></select></div>',
  '<div class="field"><label>主な産業（カンマ区切り）</label><input type="text" id="cityEditIndustries" placeholder="例: 漁業, 観光" /></div>',
  "</div>",
  '<div class="field"><label>説明</label><textarea id="cityEditDescription" style="min-height:4em"></textarea></div>',
  '<div class="row"><button onclick="saveCity()">保存</button><button class="secondary" onclick="closeCityEditor()">閉じる</button>' +
    '<button class="secondary hidden" id="cityDeleteBtn" onclick="deleteCityFromEditor()" style="color:var(--bad)">削除</button></div>',
  '<div id="cityEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",

  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  '<h3 style="margin:0">施設一覧</h3>',
  '<button onclick="showFacilityCreateForm()">+ 新しい施設を追加</button>',
  "</div>",
  '<div class="sub">住宅街・大学・公園・商店街など、雇用主ではない施設です。都市を作成すると住宅街・商店街が自動的に用意されます。</div>',
  '<div class="field" style="max-width:320px;margin-top:0.6rem"><label>都市で絞込</label><select id="facilityFilterCity" onchange="loadFacilitiesAdmin()"></select></div>',
  '<table style="margin-top:0.6rem"><thead><tr><th>施設名</th><th>種別</th><th>都市</th><th></th></tr></thead><tbody id="facilitiesAdminBody"></tbody></table>',
  "</div>",

  '<div class="panel editor hidden" id="facilityEditor">',
  '<h3 id="facilityEditorTitle">施設を編集</h3>',
  '<div class="field-row">',
  '<div class="field"><label>施設名</label><input type="text" id="facilityEditName" /></div>',
  '<div class="field"><label>種別</label><select id="facilityEditKind"></select></div>',
  '<div class="field" id="facilityEditCityField"><label>所在都市</label><select id="facilityEditCity"></select></div>',
  "</div>",
  '<div class="field"><label>説明</label><textarea id="facilityEditDescription" style="min-height:4em"></textarea></div>',
  '<div class="row"><button onclick="saveFacility()">保存</button><button class="secondary" onclick="closeFacilityEditor()">閉じる</button>' +
    '<button class="secondary hidden" id="facilityDeleteBtn" onclick="deleteFacilityFromEditor()" style="color:var(--bad)">削除</button></div>',
  '<div id="facilityEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",

  // --- 設定タブ ---
  '<div class="tab-panel" data-tab-panel="settings">',
  '<div class="panel">',
  "<h3>自動配信時刻</h3>",
  '<div class="sub">JST(日本時間)。ここを保存すると、最大10分以内に反映されます（再デプロイ不要）。</div>',
  '<div id="timeChips" class="row" style="margin-bottom:0.6rem"></div>',
  '<div class="row">',
  '<button class="secondary" onclick="addTimeChip(\'12:00\')">+ 時刻を追加</button>',
  '<button onclick="saveSettings()">設定を保存</button>',
  "</div>",
  '<div id="settingsMsg" class="sub" style="margin-top:0.5rem"></div>',
  "</div>",
  '<div class="panel">',
  "<h3>天気・気候</h3>",
  '<div class="field" style="max-width:320px">',
  '<label>現在の天候</label>',
  '<div class="row"><select id="weatherInput"></select><button onclick="saveWeather()">更新</button></div>',
  "</div>",
  '<div id="weatherMsg" class="sub"></div>',
  "</div>",
  '<div class="panel">',
  "<h3>X（旧Twitter）への日次まとめ投稿</h3>",
  '<div class="sub">毎朝8:00(JST)に、前日公開分のニュースをAIが要約してXへ自動投稿します。' +
    "X_API_KEY等4つのシークレットが未設定の場合は投稿がスキップされます。下のボタンでCronを待たずに今すぐ試せます。</div>",
  '<div class="row"><button class="secondary" onclick="testTweetDigest()">今すぐ投稿をテスト</button></div>',
  '<div id="tweetDigestMsg" class="sub" style="margin-top:0.5rem"></div>',
  "</div>",
  "</div>",

  "</div>", // #dashboard
  "</div>", // .wrap
].join("\n");

// クライアント側スクリプト。テンプレートリテラルの混乱を避けるため
// バッククォートは使わず文字列結合のみで記述する。
const SCRIPT = [
  "var TOKEN_KEY = 'odorokinews_admin_token';",
  "",
  "function getToken() { try { return localStorage.getItem(TOKEN_KEY); } catch (e) { return null; } }",
  "function setToken(v) { try { localStorage.setItem(TOKEN_KEY, v); } catch (e) {} }",
  "function clearToken() { try { localStorage.removeItem(TOKEN_KEY); } catch (e) {} }",
  "",
  "function escapeHtml(s) {",
  "  return String(s == null ? '' : s)",
  "    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');",
  "}",
  "",
  "function showTab(name) {",
  "  document.querySelectorAll('.tab-btn').forEach(function (b) { b.classList.toggle('active', b.getAttribute('data-tab') === name); });",
  "  document.querySelectorAll('.tab-panel').forEach(function (p) { p.classList.toggle('active', p.getAttribute('data-tab-panel') === name); });",
  "}",
  "",
  "var pollTimer = null;",
  "",
  "function saveToken() {",
  "  var v = document.getElementById('tokenInput').value.trim();",
  "  if (!v) return;",
  "  setToken(v);",
  "  document.getElementById('loginError').textContent = '';",
  "  refresh();",
  "}",
  "",
  "function logout() {",
  "  clearToken();",
  "  if (pollTimer) clearInterval(pollTimer);",
  "  document.getElementById('dashboard').classList.add('hidden');",
  "  document.getElementById('loginPanel').classList.remove('hidden');",
  "}",
  "",
  "function fetchStatus() {",
  "  var token = getToken();",
  "  if (!token) return Promise.reject(new Error('no token'));",
  "  return fetch('/api/admin/status', { headers: { 'x-admin-token': token } }).then(function (res) {",
  "    if (!res.ok) throw new Error('status ' + res.status);",
  "    return res.json();",
  "  });",
  "}",
  "",
  "function renderStatus(data) {",
  "  document.getElementById('loginPanel').classList.add('hidden');",
  "  document.getElementById('dashboard').classList.remove('hidden');",
  "",
  "  var grid = document.getElementById('statGrid');",
  "  var lastRun = data.recentRuns[0];",
  "  var stats = [",
  "    ['世界暦', data.world ? data.world.current_date : '-'],",
  "    ['最終実行の状態', lastRun ? lastRun.status : '-'],",
  "    ['最終実行日時 (UTC)', lastRun ? lastRun.started_at : '-'],",
  "    ['自動実行スケジュール', data.schedule.join(' / ')],",
  "  ];",
  "  grid.innerHTML = stats.map(function (s) {",
  "    return '<div class=\"stat\"><div class=\"label\">' + escapeHtml(s[0]) + '</div><div class=\"value\">' + escapeHtml(s[1]) + '</div></div>';",
  "  }).join('');",
  "",
  "  var body = document.getElementById('runsBody');",
  "  body.innerHTML = data.recentRuns.map(function (r) {",
  "    var badgeClass = r.status === 'success' ? 'success' : (r.status === 'failed' ? 'failed' : 'running');",
  "    return '<tr>' +",
  "      '<td>' + escapeHtml(r.world_date) + '</td>' +",
  "      '<td><span class=\"badge ' + badgeClass + '\">' + escapeHtml(r.status) + '</span></td>' +",
  "      '<td>' + escapeHtml(r.ai_calls_used) + '</td>' +",
  "      '<td>' + escapeHtml(r.started_at) + '</td>' +",
  "      '<td class=\"error-text\">' + escapeHtml(r.error || '') + '</td>' +",
  "      '</tr>';",
  "  }).join('') || '<tr><td colspan=\"5\" class=\"sub\">まだ実行履歴がありません</td></tr>';",
  "",
  "  var newsList = document.getElementById('newsList');",
  "  if (data.recentNews.length === 0) {",
  "    newsList.textContent = 'まだニュースがありません。';",
  "  } else {",
  "    newsList.innerHTML = data.recentNews.map(function (n) {",
  "      return '<div style=\"margin-bottom:0.5rem\"><a href=\"/news/' + n.id + '\" target=\"_blank\">' + escapeHtml(n.title) + '</a>' +",
  "        ' <span class=\"sub\">(' + escapeHtml(n.occurred_at) + ' / ' + escapeHtml(n.category) + ')</span></div>';",
  "    }).join('');",
  "  }",
  "",
  "  document.getElementById('lastUpdated').textContent = '最終更新: ' + new Date().toLocaleTimeString('ja-JP');",
  "  loadAdminPanels();",
  "}",
  "",
  "function refresh() {",
  "  fetchStatus().then(renderStatus).catch(function (err) {",
  "    if (String(err.message).indexOf('401') !== -1 || String(err.message).indexOf('404') !== -1) {",
  "      clearToken();",
  "      document.getElementById('loginError').textContent = 'トークンが正しくないか、設定されていません。';",
  "      document.getElementById('dashboard').classList.add('hidden');",
  "      document.getElementById('loginPanel').classList.remove('hidden');",
  "      if (pollTimer) clearInterval(pollTimer);",
  "    }",
  "  });",
  "}",
  "",
  "function runSimulation() {",
  "  var token = getToken();",
  "  if (!token) return;",
  "  var btn = document.getElementById('simulateBtn');",
  "  var msg = document.getElementById('actionMsg');",
  "  btn.disabled = true;",
  "  msg.textContent = '実行中...';",
  "  fetch('/api/admin/simulate', { method: 'POST', headers: { 'x-admin-token': token } })",
  "    .then(function (res) { return res.json().then(function (body) { return { ok: res.ok, body: body }; }); })",
  "    .then(function (r) {",
  "      if (r.body.skipped) {",
  "        msg.textContent = 'スキップ: ' + (r.body.reason || '') ;",
  "      } else if (r.body.error) {",
  "        msg.textContent = 'エラー: ' + r.body.error;",
  "      } else {",
  "        msg.textContent = '生成完了 (world_date=' + r.body.worldDate + ', source=' + r.body.source + ')';",
  "      }",
  "      refresh();",
  "    })",
  "    .catch(function (err) { msg.textContent = '通信エラー: ' + err.message; })",
  "    .finally(function () { btn.disabled = false; });",
  "}",
  "",
  "// ---- 共通API呼び出しヘルパー ----",
  "function apiCall(path, method, body) {",
  "  var token = getToken();",
  "  var opts = { method: method || 'GET', headers: { 'x-admin-token': token } };",
  "  if (body !== undefined) {",
  "    opts.headers['content-type'] = 'application/json';",
  "    opts.body = JSON.stringify(body);",
  "  }",
  "  return fetch(path, opts).then(function (res) {",
  "    return res.json().catch(function () { return {}; }).then(function (data) {",
  "      if (!res.ok) throw new Error(data.error || ('HTTP ' + res.status));",
  "      return data;",
  "    });",
  "  });",
  "}",
  "",
  "function fillSelect(el, options, selected) {",
  "  el.innerHTML = options.map(function (o) {",
  "    var value = typeof o === 'object' ? o.value : o;",
  "    var label = typeof o === 'object' ? o.label : o;",
  "    var sel = String(value) === String(selected) ? ' selected' : '';",
  "    return '<option value=\"' + escapeHtml(value) + '\"' + sel + '>' + escapeHtml(label) + '</option>';",
  "  }).join('');",
  "}",
  "function personStatusOptions() {",
  "  return window.__PERSON_STATUSES__.map(function (s) { return { value: s, label: window.__PERSON_STATUS_LABEL__[s] || s }; });",
  "}",
  "function orgStatusOptions() {",
  "  return window.__ORG_STATUSES__.map(function (s) { return { value: s, label: window.__ORG_STATUS_LABEL__[s] || s }; });",
  "}",
  "function orgKindOptions() {",
  "  return window.__ORG_KINDS__.map(function (k) { return { value: k, label: window.__ORG_KIND_LABEL__[k] || k }; });",
  "}",
  "function cityStatusOptions() {",
  "  return window.__CITY_STATUSES__.map(function (s) { return { value: s, label: window.__CITY_STATUS_LABEL__[s] || s }; });",
  "}",
  "",
  "var orgsCache = [];",
  "var occupationTypesCache = [];",
  "var panelsLoaded = false;",
  "",
  "function loadAdminPanels() {",
  "  if (panelsLoaded) return;",
  "  panelsLoaded = true;",
  "  loadSettings();",
  "  loadNewsAdmin();",
  "  loadEconAdmin();",
  "  loadCitiesAdmin();",
  "  loadOccupationTypes();",
  "  fillSelect(document.getElementById('peopleFilterStatus'), [{ value: '', label: 'すべて' }].concat(personStatusOptions()), '');",
  "  searchPeopleAdmin();",
  "}",
  "",
  "// ---- 自動配信時刻 ----",
  "function renderTimeChips(times) {",
  "  var wrap = document.getElementById('timeChips');",
  "  wrap.innerHTML = '';",
  "  times.forEach(function (t) { addTimeChip(t); });",
  "}",
  "function addTimeChip(value) {",
  "  var wrap = document.getElementById('timeChips');",
  "  var chip = document.createElement('span');",
  "  chip.className = 'time-chip';",
  "  var input = document.createElement('input');",
  "  input.type = 'text'; input.value = value; input.placeholder = 'HH:MM';",
  "  var removeBtn = document.createElement('button');",
  "  removeBtn.type = 'button'; removeBtn.textContent = '×';",
  "  removeBtn.addEventListener('click', function () { chip.remove(); });",
  "  chip.appendChild(input); chip.appendChild(removeBtn);",
  "  wrap.appendChild(chip);",
  "}",
  "function loadSettings() {",
  "  apiCall('/api/admin/settings').then(function (data) {",
  "    renderTimeChips(data.autoPublishTimes || []);",
  "    fillSelect(document.getElementById('weatherInput'), window.__WEATHER_CONDITIONS__, data.weather);",
  "  }).catch(function (err) { document.getElementById('settingsMsg').textContent = 'エラー: ' + err.message; });",
  "}",
  "function saveSettings() {",
  "  var inputs = document.querySelectorAll('#timeChips input');",
  "  var times = Array.prototype.map.call(inputs, function (i) { return i.value.trim(); }).filter(Boolean);",
  "  var msg = document.getElementById('settingsMsg');",
  "  msg.textContent = '保存中...';",
  "  apiCall('/api/admin/settings', 'PUT', { autoPublishTimes: times })",
  "    .then(function () { msg.textContent = '保存しました。最大10分で反映されます。'; })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function saveWeather() {",
  "  var msg = document.getElementById('weatherMsg');",
  "  msg.textContent = '保存中...';",
  "  apiCall('/api/admin/weather', 'PUT', { weather: document.getElementById('weatherInput').value })",
  "    .then(function () { msg.textContent = '天候を更新しました。'; })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function testTweetDigest() {",
  "  var msg = document.getElementById('tweetDigestMsg');",
  "  msg.textContent = '投稿中...';",
  "  apiCall('/api/admin/social/tweet-digest', 'POST').then(function (r) {",
  "    if (r.posted) {",
  "      msg.textContent = '投稿しました（' + r.newsCount + '件のニュースを要約）: ' + r.tweetText;",
  "    } else {",
  "      msg.textContent = '投稿されませんでした: ' + (r.reason || '不明なエラー');",
  "    }",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- ニュース管理 ----",
  "function loadNewsAdmin() {",
  "  apiCall('/api/admin/news-list').then(function (data) {",
  "    var body = document.getElementById('newsAdminBody');",
  "    body.innerHTML = (data.news || []).map(function (n) {",
  "      return '<tr class=\"clickable\" onclick=\"openNewsEditor(' + n.id + ')\">' +",
  "        '<td>' + escapeHtml(n.title) + '</td><td>' + escapeHtml(n.category) + '</td>' +",
  "        '<td>' + escapeHtml(n.published_at) + '</td></tr>';",
  "    }).join('') || '<tr><td colspan=\"3\" class=\"sub\">ニュースがありません</td></tr>';",
  "  });",
  "}",
  "var editingNewsId = null;",
  "var newsEditSelectedReporter = null;",
  "var newsEditReporterSearchResults = [];",
  "function searchNewsEditReporterCandidates() {",
  "  var q = document.getElementById('newsEditReporterSearch').value.trim();",
  "  var results = document.getElementById('newsEditReporterResults');",
  "  var url = '/api/admin/people-list?occupation=' + encodeURIComponent('記者');",
  "  if (q) url += '&q=' + encodeURIComponent(q);",
  "  apiCall(url).then(function (data) {",
  "    newsEditReporterSearchResults = data.people || [];",
  "    results.innerHTML = newsEditReporterSearchResults.map(function (p, i) {",
  "      return '<div style=\"cursor:pointer\" onclick=\"selectNewsEditReporterByIndex(' + i + ')\">+ ' + escapeHtml(p.name) + '</div>';",
  "    }).join('') || '<div class=\"sub\">記者がいません（職業タイプ管理から「記者」を職業に持つ人物を用意してください）</div>';",
  "  });",
  "}",
  "function selectNewsEditReporterByIndex(i) {",
  "  var p = newsEditReporterSearchResults[i];",
  "  if (!p) return;",
  "  newsEditSelectedReporter = { id: p.id, name: p.name };",
  "  document.getElementById('newsEditReporterSelected').textContent = '選択中: ' + p.name;",
  "  document.getElementById('newsEditReporterResults').innerHTML = '';",
  "  document.getElementById('newsEditReporterSearch').value = p.name;",
  "}",
  "function clearNewsEditReporter() {",
  "  newsEditSelectedReporter = null;",
  "  document.getElementById('newsEditReporterSearch').value = '';",
  "  document.getElementById('newsEditReporterSelected').textContent = '（未指定）';",
  "}",
  "function openNewsEditor(id) {",
  "  editingNewsId = id;",
  "  apiCall('/api/admin/news/' + id).then(function (n) {",
  "    fillSelect(document.getElementById('newsEditCategory'), window.__NEWS_CATEGORIES__, n.category);",
  "    document.getElementById('newsEditTitle').value = n.title;",
  "    document.getElementById('newsEditBody').value = n.body;",
  "    if (n.reporter_person_id && n.reporter_name) {",
  "      newsEditSelectedReporter = { id: n.reporter_person_id, name: n.reporter_name };",
  "      document.getElementById('newsEditReporterSearch').value = n.reporter_name;",
  "      document.getElementById('newsEditReporterSelected').textContent = '選択中: ' + n.reporter_name;",
  "    } else {",
  "      clearNewsEditReporter();",
  "    }",
  "    document.getElementById('newsEditReporterResults').innerHTML = '';",
  "    document.getElementById('newsEditMsg').textContent = '';",
  "    document.getElementById('newsEditor').classList.remove('hidden');",
  "  });",
  "}",
  "function closeNewsEditor() {",
  "  editingNewsId = null;",
  "  document.getElementById('newsEditor').classList.add('hidden');",
  "}",
  "function saveNews() {",
  "  if (!editingNewsId) return;",
  "  var msg = document.getElementById('newsEditMsg');",
  "  msg.textContent = '保存中...';",
  "  apiCall('/api/admin/news/' + editingNewsId, 'PUT', {",
  "    title: document.getElementById('newsEditTitle').value,",
  "    body: document.getElementById('newsEditBody').value,",
  "    category: document.getElementById('newsEditCategory').value,",
  "    reporterId: newsEditSelectedReporter ? newsEditSelectedReporter.id : null,",
  "  }).then(function () {",
  "    msg.textContent = '保存しました。';",
  "    loadNewsAdmin();",
  "    refresh();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function deleteNewsItem() {",
  "  if (!editingNewsId) return;",
  "  if (!confirm('このニュースを削除しますか？対応する出来事の記録も削除されます（人物・経済への既適用の影響は取り消されません）。')) return;",
  "  var msg = document.getElementById('newsEditMsg');",
  "  msg.textContent = '削除中...';",
  "  apiCall('/api/admin/news/' + editingNewsId, 'DELETE').then(function () {",
  "    closeNewsEditor();",
  "    loadNewsAdmin();",
  "    refresh();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- ニュースの作成（AI補助・完全手動） ----",
  "var newsCreateSelectedPeople = [];",
  "function showNewsCreateForm() {",
  "  newsCreateSelectedPeople = [];",
  "  document.getElementById('newsCreatePeopleSearch').value = '';",
  "  document.getElementById('newsCreatePeopleResults').innerHTML = '';",
  "  renderNewsCreateSelectedPeople();",
  "  renderNewsCreateOrgChecklist();",
  "  clearNewsCreateReporter();",
  "  document.getElementById('newsCreateMode').value = 'ai';",
  "  onNewsCreateModeChange();",
  "  fillSelect(document.getElementById('newsCreateGenre'), [{ value: '', label: '（指定なし・AIに任せる）' }].concat(window.__NEWS_CATEGORIES__), '');",
  "  document.getElementById('newsCreateKeywords').value = '';",
  "  document.getElementById('newsCreateTitle').value = '';",
  "  document.getElementById('newsCreateBody').value = '';",
  "  fillSelect(document.getElementById('newsCreateCategory'), window.__NEWS_CATEGORIES__, '社会');",
  "  document.getElementById('stateChangeRows').innerHTML = '';",
  "  document.getElementById('newsCreateMsg').textContent = '';",
  "  document.getElementById('newsCreator').classList.remove('hidden');",
  "  document.getElementById('newsCreator').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function closeNewsCreator() {",
  "  document.getElementById('newsCreator').classList.add('hidden');",
  "}",
  "function onNewsCreateModeChange() {",
  "  var mode = document.getElementById('newsCreateMode').value;",
  "  document.getElementById('newsCreateAiFields').classList.toggle('hidden', mode !== 'ai');",
  "  document.getElementById('newsCreateManualFields').classList.toggle('hidden', mode !== 'manual');",
  "}",
  "var newsCreatePeopleSearchResults = [];",
  "function searchNewsCreatePeople() {",
  "  var q = document.getElementById('newsCreatePeopleSearch').value.trim();",
  "  var results = document.getElementById('newsCreatePeopleResults');",
  "  if (!q) { results.innerHTML = ''; newsCreatePeopleSearchResults = []; return; }",
  "  apiCall('/api/admin/people-list?q=' + encodeURIComponent(q)).then(function (data) {",
  "    newsCreatePeopleSearchResults = data.people || [];",
  "    results.innerHTML = newsCreatePeopleSearchResults.map(function (p, i) {",
  "      var already = newsCreateSelectedPeople.some(function (x) { return x.id === p.id; });",
  "      return '<div style=\"cursor:pointer\" onclick=\"toggleNewsCreatePersonByIndex(' + i + ')\">' +",
  "        (already ? '✓ ' : '+ ') + escapeHtml(p.name) + (p.occupation ? '（' + escapeHtml(p.occupation) + '）' : '') + '</div>';",
  "    }).join('') || '<div class=\"sub\">該当なし</div>';",
  "  });",
  "}",
  "function toggleNewsCreatePersonByIndex(i) {",
  "  var p = newsCreatePeopleSearchResults[i];",
  "  if (!p) return;",
  "  toggleNewsCreatePersonById(p.id, p.name);",
  "}",
  "function toggleNewsCreatePersonById(id, name) {",
  "  var idx = -1;",
  "  newsCreateSelectedPeople.forEach(function (p, i) { if (p.id === id) idx = i; });",
  "  if (idx >= 0) { newsCreateSelectedPeople.splice(idx, 1); }",
  "  else { newsCreateSelectedPeople.push({ id: id, name: name }); }",
  "  renderNewsCreateSelectedPeople();",
  "  searchNewsCreatePeople();",
  "}",
  "function removeNewsCreatePersonByIndex(i) {",
  "  newsCreateSelectedPeople.splice(i, 1);",
  "  renderNewsCreateSelectedPeople();",
  "}",
  "function renderNewsCreateSelectedPeople() {",
  "  document.getElementById('newsCreatePeopleSelected').innerHTML = newsCreateSelectedPeople.map(function (p, i) {",
  "    return '<span class=\"time-chip\">' + escapeHtml(p.name) + '<button type=\"button\" onclick=\"removeNewsCreatePersonByIndex(' + i + ')\">×</button></span>';",
  "  }).join('');",
  "  refreshStateChangeTargets();",
  "}",
  "function renderNewsCreateOrgChecklist() {",
  "  var wrap = document.getElementById('newsCreateOrgChecklist');",
  "  wrap.innerHTML = orgsCache.map(function (o) {",
  "    return '<label style=\"display:inline-flex;align-items:center;gap:0.3rem;margin:0 0.8rem 0.4rem 0\">' +",
  "      '<input type=\"checkbox\" class=\"newsCreateOrgCheckbox\" value=\"' + o.id + '\" onchange=\"refreshStateChangeTargets()\" /> ' + escapeHtml(o.name) + '</label>';",
  "  }).join('') || '<span class=\"sub\">\u4f01\u696d\u304c\u3042\u308a\u307e\u305b\u3093</span>';",
  "}",
  "function selectedNewsCreateOrgIds() {",
  "  return Array.prototype.map.call(document.querySelectorAll('.newsCreateOrgCheckbox:checked'), function (el) { return Number(el.value); });",
  "}",
  "var newsCreateSelectedReporter = null;",
  "var newsCreateReporterSearchResults = [];",
  "function searchNewsCreateReporterCandidates() {",
  "  var q = document.getElementById('newsCreateReporterSearch').value.trim();",
  "  var results = document.getElementById('newsCreateReporterResults');",
  "  var url = '/api/admin/people-list?occupation=' + encodeURIComponent('記者');",
  "  if (q) url += '&q=' + encodeURIComponent(q);",
  "  apiCall(url).then(function (data) {",
  "    newsCreateReporterSearchResults = data.people || [];",
  "    results.innerHTML = newsCreateReporterSearchResults.map(function (p, i) {",
  "      return '<div style=\"cursor:pointer\" onclick=\"selectNewsCreateReporterByIndex(' + i + ')\">+ ' + escapeHtml(p.name) + '</div>';",
  "    }).join('') || '<div class=\"sub\">記者がいません</div>';",
  "  });",
  "}",
  "function selectNewsCreateReporterByIndex(i) {",
  "  var p = newsCreateReporterSearchResults[i];",
  "  if (!p) return;",
  "  newsCreateSelectedReporter = { id: p.id, name: p.name };",
  "  document.getElementById('newsCreateReporterSelected').textContent = '選択中: ' + p.name;",
  "  document.getElementById('newsCreateReporterResults').innerHTML = '';",
  "  document.getElementById('newsCreateReporterSearch').value = p.name;",
  "}",
  "function clearNewsCreateReporter() {",
  "  newsCreateSelectedReporter = null;",
  "  document.getElementById('newsCreateReporterSearch').value = '';",
  "  document.getElementById('newsCreateReporterResults').innerHTML = '';",
  "  document.getElementById('newsCreateReporterSelected').textContent = '（未指定・自動で割り当てられます）';",
  "}",
  "var stateChangeCounter = 0;",
  "function addStateChangeRow() {",
  "  var id = 'sc-' + (stateChangeCounter++);",
  "  var wrap = document.createElement('div');",
  "  wrap.className = 'row';",
  "  wrap.id = id;",
  "  wrap.style.marginBottom = '0.4rem';",
  "  wrap.innerHTML =",
  "    '<select class=\"sc-type\" onchange=\"onStateChangeTypeChange(\\'' + id + '\\')\" style=\"max-width:9em\">' +",
  "      '<option value=\"person_status\">\u4eba\u7269\u306e\u72b6\u614b</option>' +",
  "      '<option value=\"organization_status\">\u7d44\u7e54\u306e\u72b6\u614b</option>' +",
  "      '<option value=\"economic_stock_price\">\u682a\u4fa1</option>' +",
  "    '</select>' +",
  "    '<select class=\"sc-target\" style=\"max-width:10em\"></select>' +",
  "    '<span class=\"sc-value-wrap\"></span>' +",
  "    '<button type=\"button\" class=\"secondary\" onclick=\"document.getElementById(\\'' + id + '\\').remove()\">\u00d7</button>';",
  "  document.getElementById('stateChangeRows').appendChild(wrap);",
  "  onStateChangeTypeChange(id);",
  "}",
  "function onStateChangeTypeChange(rowId) {",
  "  var row = document.getElementById(rowId);",
  "  if (!row) return;",
  "  var type = row.querySelector('.sc-type').value;",
  "  var targetSel = row.querySelector('.sc-target');",
  "  var valueWrap = row.querySelector('.sc-value-wrap');",
  "  valueWrap.innerHTML = '';",
  "  if (type === 'person_status') {",
  "    fillSelect(targetSel, newsCreateSelectedPeople.map(function (p) { return { value: p.id, label: p.name }; }), '');",
  "    var sel = document.createElement('select');",
  "    sel.className = 'sc-value';",
  "    fillSelect(sel, personStatusOptions(), 'injured');",
  "    valueWrap.appendChild(sel);",
  "  } else if (type === 'organization_status') {",
  "    var orgOpts = orgsCache.filter(function (o) { return selectedNewsCreateOrgIds().indexOf(o.id) !== -1; })",
  "      .map(function (o) { return { value: o.id, label: o.name }; });",
  "    fillSelect(targetSel, orgOpts, '');",
  "    var sel2 = document.createElement('select');",
  "    sel2.className = 'sc-value';",
  "    fillSelect(sel2, orgStatusOptions(), 'under_investigation');",
  "    valueWrap.appendChild(sel2);",
  "  } else {",
  "    var orgOpts2 = orgsCache.filter(function (o) { return selectedNewsCreateOrgIds().indexOf(o.id) !== -1; })",
  "      .map(function (o) { return { value: o.id, label: o.name }; });",
  "    fillSelect(targetSel, orgOpts2, '');",
  "    var inp = document.createElement('input');",
  "    inp.type = 'number'; inp.step = '0.01'; inp.className = 'sc-value';",
  "    valueWrap.appendChild(inp);",
  "  }",
  "}",
  "function refreshStateChangeTargets() {",
  "  document.querySelectorAll('#stateChangeRows > div').forEach(function (row) { onStateChangeTypeChange(row.id); });",
  "}",
  "function collectStateChangeRows() {",
  "  var rows = document.querySelectorAll('#stateChangeRows > div');",
  "  var out = [];",
  "  rows.forEach(function (row) {",
  "    var type = row.querySelector('.sc-type').value;",
  "    var targetEl = row.querySelector('.sc-target');",
  "    var valueEl = row.querySelector('.sc-value');",
  "    if (!targetEl || !targetEl.value || !valueEl) return;",
  "    var target = Number(targetEl.value);",
  "    var value = type === 'economic_stock_price' ? Number(valueEl.value) : valueEl.value;",
  "    if (type === 'economic_stock_price' && (!value || value <= 0)) return;",
  "    out.push({ type: type, target_id: target, value: value });",
  "  });",
  "  return out;",
  "}",
  "function submitNewsCreate() {",
  "  var mode = document.getElementById('newsCreateMode').value;",
  "  var msg = document.getElementById('newsCreateMsg');",
  "  var peopleIds = newsCreateSelectedPeople.map(function (p) { return p.id; });",
  "  var orgIds = selectedNewsCreateOrgIds();",
  "  msg.textContent = mode === 'ai' ? 'AI\u306b\u4f9d\u983c\u4e2d...\uff08\u6570\u79d2\u304b\u304b\u308a\u307e\u3059\uff09' : '\u4f5c\u6210\u4e2d...';",
  "  var reporterId = newsCreateSelectedReporter ? newsCreateSelectedReporter.id : null;",
  "  var req = mode === 'ai'",
  "    ? apiCall('/api/admin/news/generate', 'POST', {",
  "        relatedPersonIds: peopleIds,",
  "        relatedOrgIds: orgIds,",
  "        genre: document.getElementById('newsCreateGenre').value || null,",
  "        keywords: document.getElementById('newsCreateKeywords').value || null,",
  "        reporterId: reporterId,",
  "      })",
  "    : apiCall('/api/admin/news/manual', 'POST', {",
  "        title: document.getElementById('newsCreateTitle').value,",
  "        body: document.getElementById('newsCreateBody').value,",
  "        category: document.getElementById('newsCreateCategory').value,",
  "        relatedPersonIds: peopleIds,",
  "        relatedOrgIds: orgIds,",
  "        stateChanges: collectStateChangeRows(),",
  "        reporterId: reporterId,",
  "      });",
  "  req.then(function () {",
  "    msg.textContent = '\u4f5c\u6210\u3057\u307e\u3057\u305f\u3002';",
  "    loadNewsAdmin();",
  "    refresh();",
  "  }).catch(function (err) { msg.textContent = '\u30a8\u30e9\u30fc: ' + err.message; });",
  "}",
  "",
  "// ---- 職業タイプ管理 ----",
  "function toggleOccupationTypesPanel() {",
  "  document.getElementById('occupationTypesPanel').classList.toggle('hidden');",
  "}",
  "function loadOccupationTypes() {",
  "  apiCall('/api/admin/occupation-types').then(function (data) {",
  "    occupationTypesCache = data.occupationTypes || [];",
  "    renderOccupationTypesList();",
  "    var filterOptions = [{ value: '', label: 'すべて' }].concat(occupationTypesCache.map(function (t) { return { value: t.name, label: t.name }; }));",
  "    fillSelect(document.getElementById('peopleFilterOccupation'), filterOptions, '');",
  "  });",
  "}",
  "function renderOccupationTypesList() {",
  "  var wrap = document.getElementById('occupationTypesList');",
  "  wrap.innerHTML = occupationTypesCache.map(function (t) {",
  "    return '<span class=\"chip\">' + escapeHtml(t.name) +",
  "      '<button type=\"button\" onclick=\"renameOccupationTypeById(' + t.id + ')\">✎</button>' +",
  "      '<button type=\"button\" onclick=\"deleteOccupationTypeById(' + t.id + ')\">×</button></span>';",
  "  }).join('') || '<span class=\"sub\">職業タイプがまだありません</span>';",
  "}",
  "function addOccupationType() {",
  "  var input = document.getElementById('newOccupationTypeName');",
  "  var name = input.value.trim();",
  "  var msg = document.getElementById('occupationTypesMsg');",
  "  if (!name) { msg.textContent = '職業名を入力してください。'; return; }",
  "  msg.textContent = '追加中...';",
  "  apiCall('/api/admin/occupation-types', 'POST', { name: name }).then(function () {",
  "    input.value = '';",
  "    msg.textContent = '追加しました。';",
  "    loadOccupationTypes();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function renameOccupationTypeById(id) {",
  "  var current = occupationTypesCache.filter(function (t) { return t.id === id; })[0];",
  "  if (!current) return;",
  "  var name = prompt('新しい職業名', current.name);",
  "  if (!name || !name.trim() || name.trim() === current.name) return;",
  "  apiCall('/api/admin/occupation-types/' + id, 'PUT', { name: name.trim() }).then(function () {",
  "    loadOccupationTypes();",
  "  }).catch(function (err) { document.getElementById('occupationTypesMsg').textContent = 'エラー: ' + err.message; });",
  "}",
  "function deleteOccupationTypeById(id) {",
  "  if (!confirm('この職業タイプを削除しますか？（既にこの職業が設定されている人物のデータ自体は変わりません）')) return;",
  "  apiCall('/api/admin/occupation-types/' + id, 'DELETE').then(function () {",
  "    loadOccupationTypes();",
  "  }).catch(function (err) { document.getElementById('occupationTypesMsg').textContent = 'エラー: ' + err.message; });",
  "}",
  "function occupationSelectOptions(currentValue) {",
  "  var options = occupationTypesCache.map(function (t) { return { value: t.name, label: t.name }; });",
  "  if (currentValue && !occupationTypesCache.some(function (t) { return t.name === currentValue; })) {",
  "    options.unshift({ value: currentValue, label: currentValue + '（未登録）' });",
  "  }",
  "  return options;",
  "}",
  "function genderSelectOptions(currentValue) {",
  "  var options = [{ value: '', label: '（未指定）' }].concat(",
  "    window.__GENDER_OPTIONS__.map(function (g) { return { value: g, label: window.__GENDER_LABEL__[g] || g }; })",
  "  );",
  "  if (currentValue && window.__GENDER_OPTIONS__.indexOf(currentValue) === -1) {",
  "    options.push({ value: currentValue, label: currentValue + '（未登録）' });",
  "  }",
  "  return options;",
  "}",
  "",
  "// ---- 人物管理 ----",
  "function searchPeopleAdmin() {",
  "  var q = document.getElementById('peopleSearchAdmin').value.trim();",
  "  var occupation = document.getElementById('peopleFilterOccupation').value;",
  "  var status = document.getElementById('peopleFilterStatus').value;",
  "  var params = [];",
  "  if (q) params.push('q=' + encodeURIComponent(q));",
  "  if (occupation) params.push('occupation=' + encodeURIComponent(occupation));",
  "  if (status) params.push('status=' + encodeURIComponent(status));",
  "  apiCall('/api/admin/people-list' + (params.length ? '?' + params.join('&') : '')).then(function (data) {",
  "    var people = data.people || [];",
  "    document.getElementById('peopleAdminCount').textContent = people.length + ' 人';",
  "    var body = document.getElementById('peopleAdminBody');",
  "    body.innerHTML = people.map(function (p) {",
  "      return '<tr class=\"clickable\" onclick=\"openPersonEditor(' + p.id + ')\">' +",
  "        '<td>' + escapeHtml(p.name) + '</td><td>' + escapeHtml(p.occupation || '') + '</td>' +",
  "        '<td>' + escapeHtml(window.__PERSON_STATUS_LABEL__[p.status] || p.status) + '</td></tr>';",
  "    }).join('') || '<tr><td colspan=\"3\" class=\"sub\">該当する人物がいません</td></tr>';",
  "  });",
  "}",
  "var editingPersonId = null;",
  "function openPersonEditor(id) {",
  "  editingPersonId = id;",
  "  apiCall('/api/admin/people/' + id).then(function (p) {",
  "    document.getElementById('personEditName').value = p.name || '';",
  "    document.getElementById('personEditKana').value = p.name_kana || '';",
  "    document.getElementById('personEditAge').value = p.age == null ? '' : p.age;",
  "    fillSelect(document.getElementById('personEditGender'), genderSelectOptions(p.gender), p.gender || '');",
  "    fillSelect(document.getElementById('personEditOccupation'), occupationSelectOptions(p.occupation), p.occupation || '');",
  "    document.getElementById('personEditJobTitle').value = p.job_title || '';",
  "    document.getElementById('personEditIncome').value = p.annual_income == null ? '' : p.annual_income;",
  "    document.getElementById('personEditBirthDate').value = p.birth_date || '';",
  "    document.getElementById('personEditBirthplace').value = p.birthplace || '';",
  "    document.getElementById('personEditMoney').value = p.money == null ? 0 : p.money;",
  "    document.getElementById('personEditBio').value = p.bio || '';",
  "    fillSelect(document.getElementById('personEditStatus'), personStatusOptions(), p.status);",
  "    var orgOptions = [{ value: '', label: '(所属なし)' }].concat(orgsCache.map(function (o) { return { value: o.id, label: o.name }; }));",
  "    fillSelect(document.getElementById('personEditOrg'), orgOptions, p.organization_id || '');",
  "    document.getElementById('personEditCityField').classList.add('hidden');",
  "    document.getElementById('personEditMsg').textContent = '';",
  "    document.getElementById('personEditor').classList.remove('hidden');",
  "    document.getElementById('personRelSection').classList.remove('hidden');",
  "    document.getElementById('personChildbirthSection').classList.remove('hidden');",
  "    resetPersonRelForm();",
  "    resetChildbirthForm();",
  "    loadPersonRelationships();",
  "  });",
  "}",
  "function showPersonCreateForm() {",
  "  editingPersonId = null;",
  "  document.getElementById('personEditName').value = '';",
  "  document.getElementById('personEditKana').value = '';",
  "  document.getElementById('personEditAge').value = '';",
  "  fillSelect(document.getElementById('personEditGender'), genderSelectOptions(null), '');",
  "  fillSelect(document.getElementById('personEditOccupation'), occupationSelectOptions(null), '');",
  "  document.getElementById('personEditJobTitle').value = '';",
  "  document.getElementById('personEditIncome').value = '';",
  "  document.getElementById('personEditBirthDate').value = '';",
  "  document.getElementById('personEditBirthplace').value = '';",
  "  document.getElementById('personEditMoney').value = 0;",
  "  document.getElementById('personEditBio').value = '';",
  "  fillSelect(document.getElementById('personEditStatus'), personStatusOptions(), 'alive');",
  "  var orgOptionsCreate = [{ value: '', label: '(所属なし)' }].concat(orgsCache.map(function (o) { return { value: o.id, label: o.name }; }));",
  "  fillSelect(document.getElementById('personEditOrg'), orgOptionsCreate, '');",
  "  var cityOptions = citiesCache.map(function (ci) { return { value: ci.id, label: ci.name + (ci.status !== 'active' ? '（準備中）' : '') }; });",
  "  fillSelect(document.getElementById('personEditCity'), cityOptions.length ? cityOptions : [{ value: 1, label: 'ダイナン市' }], 1);",
  "  document.getElementById('personEditCityField').classList.remove('hidden');",
  "  document.getElementById('personEditMsg').textContent = '';",
  "  document.getElementById('personEditor').classList.remove('hidden');",
  "  document.getElementById('personRelSection').classList.add('hidden');",
  "  document.getElementById('personChildbirthSection').classList.add('hidden');",
  "  document.getElementById('personEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function closePersonEditor() {",
  "  editingPersonId = null;",
  "  document.getElementById('personEditor').classList.add('hidden');",
  "}",
  "function savePerson() {",
  "  var msg = document.getElementById('personEditMsg');",
  "  msg.textContent = '保存中...';",
  "  var orgVal = document.getElementById('personEditOrg').value;",
  "  var ageVal = document.getElementById('personEditAge').value;",
  "  var incomeVal = document.getElementById('personEditIncome').value;",
  "  var payload = {",
  "    name: document.getElementById('personEditName').value,",
  "    name_kana: document.getElementById('personEditKana').value,",
  "    age: ageVal === '' ? null : Number(ageVal),",
  "    gender: document.getElementById('personEditGender').value,",
  "    occupation: document.getElementById('personEditOccupation').value,",
  "    job_title: document.getElementById('personEditJobTitle').value,",
  "    annual_income: incomeVal === '' ? null : Number(incomeVal),",
  "    birth_date: document.getElementById('personEditBirthDate').value,",
  "    birthplace: document.getElementById('personEditBirthplace').value,",
  "    organization_id: orgVal === '' ? null : Number(orgVal),",
  "    money: Number(document.getElementById('personEditMoney').value || 0),",
  "    status: document.getElementById('personEditStatus').value,",
  "    bio: document.getElementById('personEditBio').value,",
  "  };",
  "  var req;",
  "  if (editingPersonId) {",
  "    req = apiCall('/api/admin/people/' + editingPersonId, 'PUT', payload);",
  "  } else {",
  "    payload.city_id = Number(document.getElementById('personEditCity').value);",
  "    req = apiCall('/api/admin/people', 'POST', payload);",
  "  }",
  "  req.then(function () {",
  "    msg.textContent = '保存しました。';",
  "    searchPeopleAdmin();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 人間関係・家系図（人物編集画面内） ----",
  "var personRelSelectedTarget = null;",
  "function resetPersonRelForm() {",
  "  personRelSelectedTarget = null;",
  "  document.getElementById('personRelSearch').value = '';",
  "  document.getElementById('personRelSearchResults').innerHTML = '';",
  "  document.getElementById('personRelSelected').textContent = '（相手を検索結果から選択してください）';",
  "  fillSelect(document.getElementById('personRelType'), window.__RELATION_TYPES__.map(function (t) { return { value: t, label: window.__RELATION_TYPE_LABEL__[t] || t }; }), 'family_parent');",
  "  document.getElementById('personRelMsg').textContent = '';",
  "}",
  "function loadPersonRelationships() {",
  "  if (!editingPersonId) return;",
  "  apiCall('/api/admin/people/' + editingPersonId + '/relationships').then(function (data) {",
  "    var body = document.getElementById('personRelBody');",
  "    body.innerHTML = (data.relationships || []).map(function (r) {",
  "      var label = window.__RELATION_TYPE_LABEL__[r.relationType] || r.relationType;",
  "      return '<tr>' +",
  "        '<td><a href=\"/people/' + r.relatedPersonId + '\" target=\"_blank\">' + escapeHtml(r.relatedPersonName) + '</a></td>' +",
  "        '<td>' + escapeHtml(label) + '</td>' +",
  "        '<td><button class=\"secondary\" onclick=\"removePersonRelationship(' + r.relatedPersonId + ', \\'' + r.relationType + '\\')\">解除</button></td>' +",
  "        '</tr>';",
  "    }).join('') || '<tr><td colspan=\"3\" class=\"sub\">まだ関係が登録されていません</td></tr>';",
  "  });",
  "}",
  "var personRelSearchResults = [];",
  "function searchPersonRelCandidates() {",
  "  var q = document.getElementById('personRelSearch').value.trim();",
  "  var results = document.getElementById('personRelSearchResults');",
  "  if (!q) { results.innerHTML = ''; personRelSearchResults = []; return; }",
  "  apiCall('/api/admin/people-list?q=' + encodeURIComponent(q)).then(function (data) {",
  "    personRelSearchResults = (data.people || []).filter(function (p) { return p.id !== editingPersonId; });",
  "    results.innerHTML = personRelSearchResults.map(function (p, i) {",
  "      return '<div style=\"cursor:pointer\" onclick=\"selectPersonRelCandidateByIndex(' + i + ')\">' +",
  "        '+ ' + escapeHtml(p.name) + (p.occupation ? '（' + escapeHtml(p.occupation) + '）' : '') + '</div>';",
  "    }).join('') || '<div class=\"sub\">該当なし</div>';",
  "  });",
  "}",
  "function selectPersonRelCandidateByIndex(i) {",
  "  var p = personRelSearchResults[i];",
  "  if (!p) return;",
  "  personRelSelectedTarget = { id: p.id, name: p.name };",
  "  document.getElementById('personRelSelected').textContent = '選択中: ' + p.name;",
  "  document.getElementById('personRelSearchResults').innerHTML = '';",
  "  document.getElementById('personRelSearch').value = p.name;",
  "}",
  "function addPersonRelationship() {",
  "  var msg = document.getElementById('personRelMsg');",
  "  if (!editingPersonId || !personRelSelectedTarget) { msg.textContent = '相手を選択してください。'; return; }",
  "  msg.textContent = '追加中...';",
  "  apiCall('/api/admin/relationships', 'POST', {",
  "    personId: editingPersonId,",
  "    relatedPersonId: personRelSelectedTarget.id,",
  "    relationType: document.getElementById('personRelType').value,",
  "  }).then(function () {",
  "    msg.textContent = '追加しました。';",
  "    resetPersonRelForm();",
  "    loadPersonRelationships();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function removePersonRelationship(relatedPersonId, relationType) {",
  "  if (!editingPersonId) return;",
  "  if (!confirm('この関係を解除しますか？')) return;",
  "  apiCall('/api/admin/relationships', 'DELETE', {",
  "    personId: editingPersonId,",
  "    relatedPersonId: relatedPersonId,",
  "    relationType: relationType,",
  "  }).then(function () {",
  "    loadPersonRelationships();",
  "  }).catch(function (err) { document.getElementById('personRelMsg').textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 出産の記録 ----",
  "var childbirthSelectedFather = null;",
  "function resetChildbirthForm() {",
  "  childbirthSelectedFather = null;",
  "  document.getElementById('childbirthName').value = '';",
  "  document.getElementById('childbirthKana').value = '';",
  "  fillSelect(document.getElementById('childbirthGender'), genderSelectOptions(null), '');",
  "  document.getElementById('childbirthFatherSearch').value = '';",
  "  document.getElementById('childbirthFatherResults').innerHTML = '';",
  "  document.getElementById('childbirthFatherSelected').textContent = '（未指定）';",
  "  document.getElementById('childbirthMsg').textContent = '';",
  "}",
  "var childbirthFatherSearchResults = [];",
  "function searchChildbirthFatherCandidates() {",
  "  var q = document.getElementById('childbirthFatherSearch').value.trim();",
  "  var results = document.getElementById('childbirthFatherResults');",
  "  if (!q) { results.innerHTML = ''; childbirthFatherSearchResults = []; return; }",
  "  apiCall('/api/admin/people-list?q=' + encodeURIComponent(q)).then(function (data) {",
  "    childbirthFatherSearchResults = (data.people || []).filter(function (p) { return p.id !== editingPersonId; });",
  "    results.innerHTML = childbirthFatherSearchResults.map(function (p, i) {",
  "      return '<div style=\"cursor:pointer\" onclick=\"selectChildbirthFatherByIndex(' + i + ')\">' +",
  "        '+ ' + escapeHtml(p.name) + (p.occupation ? '（' + escapeHtml(p.occupation) + '）' : '') + '</div>';",
  "    }).join('') || '<div class=\"sub\">該当なし</div>';",
  "  });",
  "}",
  "function selectChildbirthFatherByIndex(i) {",
  "  var p = childbirthFatherSearchResults[i];",
  "  if (!p) return;",
  "  childbirthSelectedFather = { id: p.id, name: p.name };",
  "  document.getElementById('childbirthFatherSelected').textContent = '選択中: ' + p.name;",
  "  document.getElementById('childbirthFatherResults').innerHTML = '';",
  "  document.getElementById('childbirthFatherSearch').value = p.name;",
  "}",
  "function submitChildbirth() {",
  "  var msg = document.getElementById('childbirthMsg');",
  "  if (!editingPersonId) return;",
  "  var name = document.getElementById('childbirthName').value.trim();",
  "  if (!name) { msg.textContent = '子の名前を入力してください。'; return; }",
  "  msg.textContent = '記録中...';",
  "  apiCall('/api/admin/people/childbirth', 'POST', {",
  "    motherId: editingPersonId,",
  "    fatherId: childbirthSelectedFather ? childbirthSelectedFather.id : null,",
  "    name: name,",
  "    name_kana: document.getElementById('childbirthKana').value,",
  "    gender: document.getElementById('childbirthGender').value,",
  "  }).then(function () {",
  "    msg.textContent = '出産を記録しました。';",
  "    resetChildbirthForm();",
  "    loadPersonRelationships();",
  "    searchPeopleAdmin();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 経済コントロール ----",
  "function loadEconAdmin() {",
  "  apiCall('/api/admin/economy-list').then(function (data) {",
  "    orgsCache = data.organizations || [];",
  "    document.getElementById('priceIndexInput').value = data.priceIndex == null ? '' : data.priceIndex;",
  "    var body = document.getElementById('econAdminBody');",
  "    body.innerHTML = orgsCache.map(function (o) {",
  "      var detail = [o.industry, o.foundedYear ? (o.foundedYear + '年創業') : null, o.employeeScale]",
  "        .filter(Boolean).join(' / ');",
  "      var priceCell = o.kind === 'company'",
  "        ? '<div class=\"row\"><input type=\"number\" step=\"0.01\" style=\"width:6.5em\" value=\"' + (o.stockPrice == null ? '' : o.stockPrice) + '\" id=\"stock-' + o.id + '\" />' +",
  "          '<button class=\"secondary\" onclick=\"saveOrgStock(' + o.id + ')\">更新</button></div>'",
  "        : '<span class=\"sub\">-</span>';",
  "      return '<tr>' +",
  "        '<td>' + escapeHtml(o.name) + (detail ? '<div class=\"org-detail\">' + escapeHtml(detail) + '</div>' : '') + '</td>' +",
  "        '<td>' + escapeHtml(window.__ORG_KIND_LABEL__[o.kind] || o.kind) + '</td>' +",
  "        '<td>' + escapeHtml(window.__ORG_STATUS_LABEL__[o.status] || o.status) + '</td>' +",
  "        '<td>' + priceCell + '</td>' +",
  "        '<td><button class=\"secondary\" onclick=\"openOrgEditor(' + o.id + ')\">編集</button></td>' +",
  "        '</tr>';",
  "    }).join('') || '<tr><td colspan=\"5\" class=\"sub\">組織がありません</td></tr>';",
  "  });",
  "}",
  "function saveOrgStock(id) {",
  "  var input = document.getElementById('stock-' + id);",
  "  var value = Number(input.value);",
  "  var msg = document.getElementById('econMsg');",
  "  if (!value || value <= 0) { msg.textContent = '正の数値を入力してください。'; return; }",
  "  apiCall('/api/admin/economy/stock', 'POST', { organization_id: id, value: value })",
  "    .then(function () { msg.textContent = '株価を更新しました。'; loadEconAdmin(); })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function savePriceIndex() {",
  "  var value = Number(document.getElementById('priceIndexInput').value);",
  "  var msg = document.getElementById('econMsg');",
  "  if (!value || value <= 0) { msg.textContent = '正の数値を入力してください。'; return; }",
  "  apiCall('/api/admin/economy/price-index', 'PUT', { value: value })",
  "    .then(function () { msg.textContent = '物価指数を更新しました。'; loadEconAdmin(); })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 企業の追加・編集 ----",
  "var editingOrgId = null;",
  "function showOrgCreateForm() {",
  "  editingOrgId = null;",
  "  document.getElementById('orgEditorTitle').textContent = '新しい企業を追加';",
  "  document.getElementById('orgEditName').value = '';",
  "  document.getElementById('orgEditIndustry').value = '';",
  "  document.getElementById('orgEditEmployeeScale').value = '';",
  "  document.getElementById('orgEditFoundedYear').value = '';",
  "  document.getElementById('orgEditDescription').value = '';",
  "  fillSelect(document.getElementById('orgEditKind'), orgKindOptions(), 'company');",
  "  fillSelect(document.getElementById('orgEditStatus'), orgStatusOptions(), 'active');",
  "  var cityOptions = citiesCache.map(function (ci) { return { value: ci.id, label: ci.name + (ci.status !== 'active' ? '（準備中）' : '') }; });",
  "  fillSelect(document.getElementById('orgEditCity'), cityOptions.length ? cityOptions : [{ value: 1, label: 'ダイナン市' }], 1);",
  "  document.getElementById('orgEditCityField').classList.remove('hidden');",
  "  document.getElementById('orgEditMsg').textContent = '';",
  "  document.getElementById('orgEditor').classList.remove('hidden');",
  "  document.getElementById('orgEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function openOrgEditor(id) {",
  "  var o = orgsCache.filter(function (x) { return x.id === id; })[0];",
  "  if (!o) return;",
  "  editingOrgId = id;",
  "  document.getElementById('orgEditorTitle').textContent = o.name + ' を編集';",
  "  document.getElementById('orgEditName').value = o.name || '';",
  "  document.getElementById('orgEditIndustry').value = o.industry || '';",
  "  document.getElementById('orgEditEmployeeScale').value = o.employeeScale || '';",
  "  document.getElementById('orgEditFoundedYear').value = o.foundedYear == null ? '' : o.foundedYear;",
  "  document.getElementById('orgEditDescription').value = o.description || '';",
  "  fillSelect(document.getElementById('orgEditKind'), orgKindOptions(), o.kind);",
  "  fillSelect(document.getElementById('orgEditStatus'), orgStatusOptions(), o.status);",
  "  var orgCityOptions = citiesCache.map(function (ci) { return { value: ci.id, label: ci.name + (ci.status !== 'active' ? '（準備中）' : '') }; });",
  "  fillSelect(document.getElementById('orgEditCity'), orgCityOptions.length ? orgCityOptions : [{ value: 1, label: 'ダイナン市' }], o.city_id || 1);",
  "  document.getElementById('orgEditCityField').classList.remove('hidden');",
  "  document.getElementById('orgEditMsg').textContent = '';",
  "  document.getElementById('orgEditor').classList.remove('hidden');",
  "  document.getElementById('orgEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function closeOrgEditor() {",
  "  editingOrgId = null;",
  "  document.getElementById('orgEditor').classList.add('hidden');",
  "}",
  "function saveOrg() {",
  "  var msg = document.getElementById('orgEditMsg');",
  "  var fy = document.getElementById('orgEditFoundedYear').value;",
  "  var payload = {",
  "    name: document.getElementById('orgEditName').value,",
  "    kind: document.getElementById('orgEditKind').value,",
  "    industry: document.getElementById('orgEditIndustry').value,",
  "    employeeScale: document.getElementById('orgEditEmployeeScale').value,",
  "    foundedYear: fy === '' ? null : Number(fy),",
  "    description: document.getElementById('orgEditDescription').value,",
  "  };",
  "  payload.city_id = Number(document.getElementById('orgEditCity').value);",
  "  msg.textContent = '保存中...';",
  "  if (editingOrgId) {",
  "    payload.status = document.getElementById('orgEditStatus').value;",
  "    apiCall('/api/admin/organizations/' + editingOrgId, 'PUT', payload).then(function (r) {",
  "      msg.textContent = r.clearedEmployees ? ('保存しました（倒産により' + r.clearedEmployees + '人が無所属になりました）') : '保存しました。';",
  "      loadEconAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  } else {",
  "    apiCall('/api/admin/organizations', 'POST', payload).then(function () {",
  "      msg.textContent = '新しい企業を追加しました。地図にも自動的に反映されます。';",
  "      loadEconAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  }",
  "}",
  "",
  "// ---- 都市管理 ----",
  "var citiesCache = [];",
  "function loadCitiesAdmin() {",
  "  apiCall('/api/admin/cities').then(function (data) {",
  "    citiesCache = data.cities || [];",
  "    var body = document.getElementById('citiesAdminBody');",
  "    body.innerHTML = citiesCache.map(function (ci) {",
  "      return '<tr>' +",
  "        '<td>' + escapeHtml(ci.name) + '</td>' +",
  "        '<td>' + escapeHtml(window.__CITY_STATUS_LABEL__[ci.status] || ci.status) + '</td>' +",
  "        '<td>' + (ci.population == null ? '-' : escapeHtml(ci.population)) + '</td>' +",
  "        '<td><button class=\"secondary\" onclick=\"openCityEditor(' + ci.id + ')\">編集</button></td>' +",
  "        '</tr>';",
  "    }).join('') || '<tr><td colspan=\"4\" class=\"sub\">都市がありません</td></tr>';",
  "    var cityFilterOptions = [{ value: '', label: 'すべて' }].concat(citiesCache.map(function (ci) { return { value: ci.id, label: ci.name }; }));",
  "    fillSelect(document.getElementById('facilityFilterCity'), cityFilterOptions, '');",
  "    loadFacilitiesAdmin();",
  "  });",
  "}",
  "var editingCityId = null;",
  "function showCityCreateForm() {",
  "  editingCityId = null;",
  "  document.getElementById('cityEditorTitle').textContent = '新しい都市を追加';",
  "  document.getElementById('cityEditName').value = '';",
  "  document.getElementById('cityEditPopulation').value = '';",
  "  document.getElementById('cityEditIndustries').value = '';",
  "  document.getElementById('cityEditDescription').value = '';",
  "  fillSelect(document.getElementById('cityEditStatus'), cityStatusOptions(), 'draft');",
  "  document.getElementById('cityEditMsg').textContent = '';",
  "  document.getElementById('cityDeleteBtn').classList.add('hidden');",
  "  document.getElementById('cityEditor').classList.remove('hidden');",
  "  document.getElementById('cityEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function openCityEditor(id) {",
  "  var ci = citiesCache.filter(function (x) { return x.id === id; })[0];",
  "  if (!ci) return;",
  "  editingCityId = id;",
  "  document.getElementById('cityEditorTitle').textContent = ci.name + ' を編集';",
  "  document.getElementById('cityEditName').value = ci.name || '';",
  "  document.getElementById('cityEditPopulation').value = ci.population == null ? '' : ci.population;",
  "  document.getElementById('cityEditIndustries').value = (ci.industries || []).join(', ');",
  "  document.getElementById('cityEditDescription').value = ci.description || '';",
  "  fillSelect(document.getElementById('cityEditStatus'), cityStatusOptions(), ci.status);",
  "  document.getElementById('cityEditMsg').textContent = '';",
  "  document.getElementById('cityDeleteBtn').classList.toggle('hidden', id === 1);",
  "  document.getElementById('cityEditor').classList.remove('hidden');",
  "  document.getElementById('cityEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function closeCityEditor() {",
  "  editingCityId = null;",
  "  document.getElementById('cityEditor').classList.add('hidden');",
  "}",
  "function deleteCityFromEditor() {",
  "  if (!editingCityId) return;",
  "  if (!confirm('この都市を削除しますか？（組織・施設・人物が1件も無い場合のみ削除できます）')) return;",
  "  var msg = document.getElementById('cityEditMsg');",
  "  msg.textContent = '削除中...';",
  "  apiCall('/api/admin/cities/' + editingCityId, 'DELETE').then(function () {",
  "    closeCityEditor();",
  "    loadCitiesAdmin();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function saveCity() {",
  "  var msg = document.getElementById('cityEditMsg');",
  "  var pop = document.getElementById('cityEditPopulation').value;",
  "  var industries = document.getElementById('cityEditIndustries').value",
  "    .split(',').map(function (s) { return s.trim(); }).filter(Boolean);",
  "  var payload = {",
  "    name: document.getElementById('cityEditName').value,",
  "    population: pop === '' ? null : Number(pop),",
  "    industries: industries,",
  "    description: document.getElementById('cityEditDescription').value,",
  "    status: document.getElementById('cityEditStatus').value,",
  "  };",
  "  msg.textContent = '保存中...';",
  "  if (editingCityId) {",
  "    apiCall('/api/admin/cities/' + editingCityId, 'PUT', payload).then(function () {",
  "      msg.textContent = '保存しました。';",
  "      loadCitiesAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  } else {",
  "    apiCall('/api/admin/cities', 'POST', payload).then(function () {",
  "      msg.textContent = '新しい都市を追加しました。地図にも自動的に反映されます。';",
  "      loadCitiesAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  }",
  "}",
  "",
  "// ---- 施設管理 ----",
  "var facilitiesCache = [];",
  "var FACILITY_KIND_LABEL = { residential: '住宅街', university: '大学', park: '公園', shopping_street: '商店街', other: 'その他' };",
  "function facilityKindOptions() {",
  "  return window.__FACILITY_KINDS__.map(function (k) { return { value: k, label: FACILITY_KIND_LABEL[k] || k }; });",
  "}",
  "function loadFacilitiesAdmin() {",
  "  var cityId = document.getElementById('facilityFilterCity').value;",
  "  apiCall('/api/admin/facilities' + (cityId ? '?cityId=' + encodeURIComponent(cityId) : '')).then(function (data) {",
  "    facilitiesCache = data.facilities || [];",
  "    var body = document.getElementById('facilitiesAdminBody');",
  "    body.innerHTML = facilitiesCache.map(function (f) {",
  "      var city = citiesCache.filter(function (ci) { return ci.id === f.city_id; })[0];",
  "      return '<tr>' +",
  "        '<td>' + escapeHtml(f.name) + '</td>' +",
  "        '<td>' + escapeHtml(FACILITY_KIND_LABEL[f.kind] || f.kind) + '</td>' +",
  "        '<td>' + escapeHtml(city ? city.name : '-') + '</td>' +",
  "        '<td><button class=\"secondary\" onclick=\"openFacilityEditor(' + f.id + ')\">編集</button></td>' +",
  "        '</tr>';",
  "    }).join('') || '<tr><td colspan=\"4\" class=\"sub\">施設がありません</td></tr>';",
  "  });",
  "}",
  "var editingFacilityId = null;",
  "function showFacilityCreateForm() {",
  "  editingFacilityId = null;",
  "  document.getElementById('facilityEditorTitle').textContent = '新しい施設を追加';",
  "  document.getElementById('facilityEditName').value = '';",
  "  document.getElementById('facilityEditDescription').value = '';",
  "  fillSelect(document.getElementById('facilityEditKind'), facilityKindOptions(), 'other');",
  "  var cityOptions = citiesCache.map(function (ci) { return { value: ci.id, label: ci.name + (ci.status !== 'active' ? '（準備中）' : '') }; });",
  "  fillSelect(document.getElementById('facilityEditCity'), cityOptions.length ? cityOptions : [{ value: 1, label: 'ダイナン市' }], 1);",
  "  document.getElementById('facilityEditCityField').classList.remove('hidden');",
  "  document.getElementById('facilityEditMsg').textContent = '';",
  "  document.getElementById('facilityDeleteBtn').classList.add('hidden');",
  "  document.getElementById('facilityEditor').classList.remove('hidden');",
  "  document.getElementById('facilityEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function openFacilityEditor(id) {",
  "  var f = facilitiesCache.filter(function (x) { return x.id === id; })[0];",
  "  if (!f) return;",
  "  editingFacilityId = id;",
  "  document.getElementById('facilityEditorTitle').textContent = f.name + ' を編集';",
  "  document.getElementById('facilityEditName').value = f.name || '';",
  "  document.getElementById('facilityEditDescription').value = f.description || '';",
  "  fillSelect(document.getElementById('facilityEditKind'), facilityKindOptions(), f.kind);",
  "  var facilityCityOptions = citiesCache.map(function (ci) { return { value: ci.id, label: ci.name + (ci.status !== 'active' ? '（準備中）' : '') }; });",
  "  fillSelect(document.getElementById('facilityEditCity'), facilityCityOptions.length ? facilityCityOptions : [{ value: 1, label: 'ダイナン市' }], f.city_id || 1);",
  "  document.getElementById('facilityEditCityField').classList.remove('hidden');",
  "  document.getElementById('facilityEditMsg').textContent = '';",
  "  document.getElementById('facilityDeleteBtn').classList.remove('hidden');",
  "  document.getElementById('facilityEditor').classList.remove('hidden');",
  "  document.getElementById('facilityEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function closeFacilityEditor() {",
  "  editingFacilityId = null;",
  "  document.getElementById('facilityEditor').classList.add('hidden');",
  "}",
  "function deleteFacilityFromEditor() {",
  "  if (!editingFacilityId) return;",
  "  if (!confirm('この施設を削除しますか？')) return;",
  "  var msg = document.getElementById('facilityEditMsg');",
  "  msg.textContent = '削除中...';",
  "  apiCall('/api/admin/facilities/' + editingFacilityId, 'DELETE').then(function () {",
  "    closeFacilityEditor();",
  "    loadFacilitiesAdmin();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function saveFacility() {",
  "  var msg = document.getElementById('facilityEditMsg');",
  "  var payload = {",
  "    name: document.getElementById('facilityEditName').value,",
  "    kind: document.getElementById('facilityEditKind').value,",
  "    description: document.getElementById('facilityEditDescription').value,",
  "  };",
  "  payload.city_id = Number(document.getElementById('facilityEditCity').value);",
  "  msg.textContent = '保存中...';",
  "  if (editingFacilityId) {",
  "    apiCall('/api/admin/facilities/' + editingFacilityId, 'PUT', payload).then(function () {",
  "      msg.textContent = '保存しました。';",
  "      loadFacilitiesAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  } else {",
  "    apiCall('/api/admin/facilities', 'POST', payload).then(function () {",
  "      msg.textContent = '新しい施設を追加しました。地図にも自動的に反映されます。';",
  "      loadFacilitiesAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  }",
  "}",
  "",
  "(function init() {",
  "  var token = getToken();",
  "  if (token) {",
  "    refresh();",
  "    pollTimer = setInterval(refresh, 10000);",
  "  }",
  "})();",
].join("\n");
