// 管理画面（/admin）。公開サイトのデザインとは切り離した、シンプルな監視・編集用ダッシュボード。
// ページ自体は誰でも開けるが、中身のデータは ADMIN_TOKEN を知っている人だけが
// 各種 /api/admin/* を叩けるため閲覧・編集できる。
// トークンはブラウザのlocalStorageにのみ保存され、サーバー側には保存しない。

import { NEWS_CATEGORIES, ORG_KINDS, ORG_STATUSES, PERSON_STATUSES } from "../constants";

export function adminDashboardPage(): string {
  const constantsScript =
    "window.__NEWS_CATEGORIES__ = " + JSON.stringify(NEWS_CATEGORIES) + ";\n" +
    "window.__PERSON_STATUSES__ = " + JSON.stringify(PERSON_STATUSES) + ";\n" +
    "window.__ORG_STATUSES__ = " + JSON.stringify(ORG_STATUSES) + ";\n" +
    "window.__ORG_KINDS__ = " + JSON.stringify(ORG_KINDS) + ";\n";

  return (
    "<!doctype html>\n" +
    '<html lang="ja">\n' +
    "<head>\n" +
    '<meta charset="utf-8" />\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1" />\n' +
    "<title>管理画面 | モーゼン・クロニクル</title>\n" +
    '<meta name="robots" content="noindex" />\n' +
    "<style>\n" +
    STYLE +
    "\n</style>\n" +
    "</head>\n" +
    "<body>\n" +
    HTML_BODY +
    "\n<script>\n" +
    constantsScript +
    SCRIPT +
    "\n</script>\n" +
    "</body>\n" +
    "</html>\n"
  );
}

const STYLE = [
  ":root { color-scheme: light dark; --bg:#0f1115; --panel:#1a1d24; --line:#2a2e38; --ink:#e8e8ea; --soft:#9a9fac; --accent:#5b8cff; --ok:#3ecf8e; --bad:#ff5d5d; --warn:#ffb84d; }",
  "* { box-sizing: border-box; }",
  "body { margin:0; background:var(--bg); color:var(--ink); font-family:'Hiragino Sans','Noto Sans JP',sans-serif; }",
  ".wrap { max-width: 960px; margin: 0 auto; padding: 1.5rem 1.2rem 4rem; }",
  "h1 { font-size: 1.3rem; margin: 0 0 0.2rem; }",
  ".sub { color: var(--soft); font-size: 0.8rem; margin-bottom: 1.4rem; }",
  ".panel { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 1rem 1.1rem; margin-bottom: 1rem; }",
  ".row { display:flex; gap:0.8rem; flex-wrap:wrap; align-items:center; }",
  "input[type=password], input[type=text] { background:#0c0e12; border:1px solid var(--line); color:var(--ink); padding:0.5rem 0.7rem; border-radius:6px; font-size:0.9rem; flex:1; min-width:200px; }",
  "button { background: var(--accent); color:#fff; border:none; padding:0.55rem 1rem; border-radius:6px; font-size:0.85rem; cursor:pointer; }",
  "button.secondary { background:#2a2e38; }",
  "button:disabled { opacity:0.5; cursor:default; }",
  ".stat-grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(160px,1fr)); gap:0.8rem; }",
  ".stat { background:#0c0e12; border:1px solid var(--line); border-radius:6px; padding:0.7rem 0.8rem; }",
  ".stat .label { font-size:0.72rem; color:var(--soft); }",
  ".stat .value { font-size:1.15rem; margin-top:0.15rem; }",
  "table { width:100%; border-collapse:collapse; font-size:0.82rem; }",
  "th, td { text-align:left; padding:0.4rem 0.5rem; border-bottom:1px solid var(--line); }",
  "th { color:var(--soft); font-weight:600; }",
  ".badge { display:inline-block; padding:0.1rem 0.5rem; border-radius:999px; font-size:0.72rem; }",
  ".badge.success { background:rgba(62,207,142,0.15); color:var(--ok); }",
  ".badge.failed { background:rgba(255,93,93,0.15); color:var(--bad); }",
  ".badge.running { background:rgba(255,184,77,0.15); color:var(--warn); }",
  ".hidden { display:none; }",
  "#loginError, #actionMsg { font-size:0.82rem; margin-top:0.5rem; }",
  "#loginError { color: var(--bad); }",
  "#actionMsg { color: var(--soft); }",
  ".error-text { color: var(--bad); font-family: monospace; font-size:0.78rem; }",
  "a { color: var(--accent); }",
  "h3 { margin-top:0; }",
  "textarea, select, input[type=number] {",
  "  background:#0c0e12; border:1px solid var(--line); color:var(--ink); padding:0.5rem 0.7rem; border-radius:6px; font-size:0.85rem;",
  "  font-family:inherit; width:100%; box-sizing:border-box;",
  "}",
  "textarea { min-height:8em; resize:vertical; }",
  ".field { margin-bottom:0.7rem; }",
  ".field label { display:block; font-size:0.75rem; color:var(--soft); margin-bottom:0.25rem; }",
  ".field-row { display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:0.7rem; }",
  "tr.clickable { cursor:pointer; }",
  "tr.clickable:hover { background:#0c0e12; }",
  ".editor { border-top:1px solid var(--line); margin-top:0.8rem; padding-top:0.8rem; }",
  ".editor.hidden { display:none; }",
  ".time-chip { display:inline-flex; align-items:center; gap:0.3rem; background:#0c0e12; border:1px solid var(--line); border-radius:6px; padding:0.3rem 0.5rem; }",
  ".time-chip input { background:transparent; border:none; color:var(--ink); width:5.5em; font-size:0.85rem; }",
  ".time-chip button { padding:0 0.4rem; background:transparent; color:var(--bad); font-size:0.9rem; }",
  ".tabs { display:flex; gap:0.4rem; flex-wrap:wrap; margin-bottom:1rem; }",
  ".tab-btn { background:#0c0e12; border:1px solid var(--line); color:var(--soft); padding:0.5rem 0.9rem; border-radius:6px 6px 0 0; }",
  ".tab-btn.active { background:var(--panel); color:var(--ink); border-bottom-color:var(--panel); font-weight:700; }",
  ".tab-panel { display:none; }",
  ".tab-panel.active { display:block; }",
  ".org-detail { font-size:0.72rem; color:var(--soft); margin-top:0.15rem; }",
].join("\n");

const HTML_BODY = [
  '<div class="wrap">',
  "<h1>モーゼン・クロニクル 管理画面</h1>",
  '<div class="sub">世界の進行状況を監視し、ニュース・人物・経済を編集できます。</div>',

  '<div class="panel" id="loginPanel">',
  '<div class="row">',
  '<input type="password" id="tokenInput" placeholder="ADMIN_TOKEN を入力" autocomplete="off" />',
  '<button onclick="saveToken()">接続</button>',
  "</div>",
  '<div id="loginError"></div>',
  "</div>",

  '<div id="dashboard" class="hidden">',

  '<div class="tabs">',
  '<button class="tab-btn active" data-tab="overview" onclick="showTab(\'overview\')">概要</button>',
  '<button class="tab-btn" data-tab="news" onclick="showTab(\'news\')">ニュース</button>',
  '<button class="tab-btn" data-tab="people" onclick="showTab(\'people\')">人物</button>',
  '<button class="tab-btn" data-tab="economy" onclick="showTab(\'economy\')">経済</button>',
  '<button class="tab-btn" data-tab="settings" onclick="showTab(\'settings\')">設定</button>',
  "</div>",

  // --- 概要タブ ---
  '<div class="tab-panel active" data-tab-panel="overview">',
  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  '<div class="row">',
  '<button onclick="runSimulation()" id="simulateBtn">今すぐニュースを生成</button>',
  '<button class="secondary" onclick="refresh()">今すぐ更新</button>',
  '<button class="secondary" onclick="logout()">ログアウト</button>',
  "</div>",
  '<div class="sub" id="lastUpdated" style="margin:0">-</div>',
  "</div>",
  '<div id="actionMsg"></div>',
  "</div>",
  '<div class="panel"><div class="stat-grid" id="statGrid"></div></div>',
  '<div class="panel">',
  "<h3>直近の実行履歴</h3>",
  '<table><thead><tr><th>世界日</th><th>状態</th><th>AI呼び出し</th><th>開始</th><th>エラー</th></tr></thead><tbody id="runsBody"></tbody></table>',
  "</div>",
  '<div class="panel"><h3>最新ニュース</h3><div id="newsList" class="sub">-</div></div>',
  "</div>",

  // --- ニュースタブ ---
  '<div class="tab-panel" data-tab-panel="news">',
  '<div class="panel">',
  "<h3>ニュース管理</h3>",
  '<table><thead><tr><th>タイトル</th><th>タグ</th><th>掲載</th></tr></thead><tbody id="newsAdminBody"></tbody></table>',
  '<div id="newsEditor" class="editor hidden">',
  '<div class="field"><label>タイトル</label><input type="text" id="newsEditTitle" /></div>',
  '<div class="field"><label>タグ</label><select id="newsEditCategory"></select></div>',
  '<div class="field"><label>本文</label><textarea id="newsEditBody"></textarea></div>',
  '<div class="row"><button onclick="saveNews()">保存</button><button class="secondary" onclick="closeNewsEditor()">閉じる</button></div>',
  '<div id="newsEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",
  "</div>",

  // --- 人物タブ ---
  '<div class="tab-panel" data-tab-panel="people">',
  '<div class="panel">',
  "<h3>人物管理</h3>",
  '<input type="text" id="peopleSearchAdmin" placeholder="名前で検索" oninput="searchPeopleAdmin()" />',
  '<table style="margin-top:0.6rem"><thead><tr><th>名前</th><th>職業</th><th>状態</th></tr></thead><tbody id="peopleAdminBody"></tbody></table>',
  '<div id="personEditor" class="editor hidden">',
  '<div class="field-row">',
  '<div class="field"><label>名前</label><input type="text" id="personEditName" /></div>',
  '<div class="field"><label>ふりがな</label><input type="text" id="personEditKana" /></div>',
  '<div class="field"><label>年齢</label><input type="number" id="personEditAge" /></div>',
  '<div class="field"><label>性別</label><input type="text" id="personEditGender" /></div>',
  '<div class="field"><label>職業</label><input type="text" id="personEditOccupation" /></div>',
  '<div class="field"><label>所属組織</label><select id="personEditOrg"></select></div>',
  '<div class="field"><label>所持金</label><input type="number" id="personEditMoney" /></div>',
  '<div class="field"><label>状態</label><select id="personEditStatus"></select></div>',
  "</div>",
  '<div class="field"><label>プロフィール</label><textarea id="personEditBio" style="min-height:4em"></textarea></div>',
  '<div class="row"><button onclick="savePerson()">保存</button><button class="secondary" onclick="closePersonEditor()">閉じる</button></div>',
  '<div id="personEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",
  "</div>",

  // --- 経済タブ ---
  '<div class="tab-panel" data-tab-panel="economy">',
  '<div class="panel">',
  '<div class="field" style="max-width:320px">',
  "<label>物価指数</label>",
  '<div class="row"><input type="number" id="priceIndexInput" step="0.1" /><button onclick="savePriceIndex()">更新</button></div>',
  "</div>",
  '<div id="econMsg" class="sub"></div>',
  "</div>",

  '<div class="panel">',
  '<div class="row" style="justify-content:space-between">',
  "<h3 style=\"margin:0\">企業・組織一覧</h3>",
  '<button onclick="showOrgCreateForm()">+ 新しい企業を追加</button>',
  "</div>",
  '<table style="margin-top:0.6rem"><thead><tr><th>企業</th><th>状態</th><th>株価</th><th></th></tr></thead><tbody id="econAdminBody"></tbody></table>',
  "</div>",

  '<div class="panel editor hidden" id="orgEditor">',
  '<h3 id="orgEditorTitle">企業を編集</h3>',
  '<div class="field-row">',
  '<div class="field"><label>名前</label><input type="text" id="orgEditName" /></div>',
  '<div class="field"><label>種別</label><select id="orgEditKind"></select></div>',
  '<div class="field"><label>業種</label><input type="text" id="orgEditIndustry" placeholder="例: 製造業、IT、物流" /></div>',
  '<div class="field"><label>規模</label><input type="text" id="orgEditEmployeeScale" placeholder="例: 数十人、数百人" /></div>',
  '<div class="field"><label>創業年</label><input type="number" id="orgEditFoundedYear" /></div>',
  '<div class="field"><label>状態</label><select id="orgEditStatus"></select></div>',
  "</div>",
  '<div class="field"><label>説明</label><textarea id="orgEditDescription" style="min-height:4em"></textarea></div>',
  '<div class="row"><button onclick="saveOrg()">保存</button><button class="secondary" onclick="closeOrgEditor()">閉じる</button></div>',
  '<div id="orgEditMsg" class="sub" style="margin-top:0.4rem"></div>',
  "</div>",
  "</div>",

  // --- 設定タブ ---
  '<div class="tab-panel" data-tab-panel="settings">',
  '<div class="panel">',
  "<h3>自動配信時刻</h3>",
  '<div class="sub">JST(日本時間)。ここを保存すると、最大10分以内に反映されます（再デプロイ不要）。</div>',
  '<div id="timeChips" class="row" style="margin-bottom:0.6rem"></div>',
  '<div class="row">',
  '<button class="secondary" onclick="addTimeChip(\'12:00\')">+ 時刻を追加</button>',
  '<button onclick="saveSettings()">設定を保存</button>',
  "</div>",
  '<div id="settingsMsg" class="sub" style="margin-top:0.5rem"></div>',
  "</div>",
  "</div>",

  "</div>", // #dashboard
  "</div>", // .wrap
].join("\n");

// クライアント側スクリプト。テンプレートリテラルの混乱を避けるため
// バッククォートは使わず文字列結合のみで記述する。
const SCRIPT = [
  "var TOKEN_KEY = 'odorokinews_admin_token';",
  "",
  "function getToken() { try { return localStorage.getItem(TOKEN_KEY); } catch (e) { return null; } }",
  "function setToken(v) { try { localStorage.setItem(TOKEN_KEY, v); } catch (e) {} }",
  "function clearToken() { try { localStorage.removeItem(TOKEN_KEY); } catch (e) {} }",
  "",
  "function escapeHtml(s) {",
  "  return String(s == null ? '' : s)",
  "    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');",
  "}",
  "",
  "function showTab(name) {",
  "  document.querySelectorAll('.tab-btn').forEach(function (b) { b.classList.toggle('active', b.getAttribute('data-tab') === name); });",
  "  document.querySelectorAll('.tab-panel').forEach(function (p) { p.classList.toggle('active', p.getAttribute('data-tab-panel') === name); });",
  "}",
  "",
  "var pollTimer = null;",
  "",
  "function saveToken() {",
  "  var v = document.getElementById('tokenInput').value.trim();",
  "  if (!v) return;",
  "  setToken(v);",
  "  document.getElementById('loginError').textContent = '';",
  "  refresh();",
  "}",
  "",
  "function logout() {",
  "  clearToken();",
  "  if (pollTimer) clearInterval(pollTimer);",
  "  document.getElementById('dashboard').classList.add('hidden');",
  "  document.getElementById('loginPanel').classList.remove('hidden');",
  "}",
  "",
  "function fetchStatus() {",
  "  var token = getToken();",
  "  if (!token) return Promise.reject(new Error('no token'));",
  "  return fetch('/api/admin/status', { headers: { 'x-admin-token': token } }).then(function (res) {",
  "    if (!res.ok) throw new Error('status ' + res.status);",
  "    return res.json();",
  "  });",
  "}",
  "",
  "function renderStatus(data) {",
  "  document.getElementById('loginPanel').classList.add('hidden');",
  "  document.getElementById('dashboard').classList.remove('hidden');",
  "",
  "  var grid = document.getElementById('statGrid');",
  "  var lastRun = data.recentRuns[0];",
  "  var stats = [",
  "    ['世界暦', data.world ? data.world.current_date : '-'],",
  "    ['最終実行の状態', lastRun ? lastRun.status : '-'],",
  "    ['最終実行日時 (UTC)', lastRun ? lastRun.started_at : '-'],",
  "    ['自動実行スケジュール', data.schedule.join(' / ')],",
  "  ];",
  "  grid.innerHTML = stats.map(function (s) {",
  "    return '<div class=\"stat\"><div class=\"label\">' + escapeHtml(s[0]) + '</div><div class=\"value\">' + escapeHtml(s[1]) + '</div></div>';",
  "  }).join('');",
  "",
  "  var body = document.getElementById('runsBody');",
  "  body.innerHTML = data.recentRuns.map(function (r) {",
  "    var badgeClass = r.status === 'success' ? 'success' : (r.status === 'failed' ? 'failed' : 'running');",
  "    return '<tr>' +",
  "      '<td>' + escapeHtml(r.world_date) + '</td>' +",
  "      '<td><span class=\"badge ' + badgeClass + '\">' + escapeHtml(r.status) + '</span></td>' +",
  "      '<td>' + escapeHtml(r.ai_calls_used) + '</td>' +",
  "      '<td>' + escapeHtml(r.started_at) + '</td>' +",
  "      '<td class=\"error-text\">' + escapeHtml(r.error || '') + '</td>' +",
  "      '</tr>';",
  "  }).join('') || '<tr><td colspan=\"5\" class=\"sub\">まだ実行履歴がありません</td></tr>';",
  "",
  "  var newsList = document.getElementById('newsList');",
  "  if (data.recentNews.length === 0) {",
  "    newsList.textContent = 'まだニュースがありません。';",
  "  } else {",
  "    newsList.innerHTML = data.recentNews.map(function (n) {",
  "      return '<div style=\"margin-bottom:0.5rem\"><a href=\"/news/' + n.id + '\" target=\"_blank\">' + escapeHtml(n.title) + '</a>' +",
  "        ' <span class=\"sub\">(' + escapeHtml(n.occurred_at) + ' / ' + escapeHtml(n.category) + ')</span></div>';",
  "    }).join('');",
  "  }",
  "",
  "  document.getElementById('lastUpdated').textContent = '最終更新: ' + new Date().toLocaleTimeString('ja-JP');",
  "  loadAdminPanels();",
  "}",
  "",
  "function refresh() {",
  "  fetchStatus().then(renderStatus).catch(function (err) {",
  "    if (String(err.message).indexOf('401') !== -1 || String(err.message).indexOf('404') !== -1) {",
  "      clearToken();",
  "      document.getElementById('loginError').textContent = 'トークンが正しくないか、設定されていません。';",
  "      document.getElementById('dashboard').classList.add('hidden');",
  "      document.getElementById('loginPanel').classList.remove('hidden');",
  "      if (pollTimer) clearInterval(pollTimer);",
  "    }",
  "  });",
  "}",
  "",
  "function runSimulation() {",
  "  var token = getToken();",
  "  if (!token) return;",
  "  var btn = document.getElementById('simulateBtn');",
  "  var msg = document.getElementById('actionMsg');",
  "  btn.disabled = true;",
  "  msg.textContent = '実行中...';",
  "  fetch('/api/admin/simulate', { method: 'POST', headers: { 'x-admin-token': token } })",
  "    .then(function (res) { return res.json().then(function (body) { return { ok: res.ok, body: body }; }); })",
  "    .then(function (r) {",
  "      if (r.body.skipped) {",
  "        msg.textContent = 'スキップ: ' + (r.body.reason || '') ;",
  "      } else if (r.body.error) {",
  "        msg.textContent = 'エラー: ' + r.body.error;",
  "      } else {",
  "        msg.textContent = '生成完了 (world_date=' + r.body.worldDate + ', source=' + r.body.source + ')';",
  "      }",
  "      refresh();",
  "    })",
  "    .catch(function (err) { msg.textContent = '通信エラー: ' + err.message; })",
  "    .finally(function () { btn.disabled = false; });",
  "}",
  "",
  "// ---- 共通API呼び出しヘルパー ----",
  "function apiCall(path, method, body) {",
  "  var token = getToken();",
  "  var opts = { method: method || 'GET', headers: { 'x-admin-token': token } };",
  "  if (body !== undefined) {",
  "    opts.headers['content-type'] = 'application/json';",
  "    opts.body = JSON.stringify(body);",
  "  }",
  "  return fetch(path, opts).then(function (res) {",
  "    return res.json().catch(function () { return {}; }).then(function (data) {",
  "      if (!res.ok) throw new Error(data.error || ('HTTP ' + res.status));",
  "      return data;",
  "    });",
  "  });",
  "}",
  "",
  "function fillSelect(el, options, selected) {",
  "  el.innerHTML = options.map(function (o) {",
  "    var value = typeof o === 'object' ? o.value : o;",
  "    var label = typeof o === 'object' ? o.label : o;",
  "    var sel = String(value) === String(selected) ? ' selected' : '';",
  "    return '<option value=\"' + escapeHtml(value) + '\"' + sel + '>' + escapeHtml(label) + '</option>';",
  "  }).join('');",
  "}",
  "",
  "var orgsCache = [];",
  "var panelsLoaded = false;",
  "",
  "function loadAdminPanels() {",
  "  if (panelsLoaded) return;",
  "  panelsLoaded = true;",
  "  loadSettings();",
  "  loadNewsAdmin();",
  "  loadEconAdmin();",
  "  searchPeopleAdmin();",
  "}",
  "",
  "// ---- 自動配信時刻 ----",
  "function renderTimeChips(times) {",
  "  var wrap = document.getElementById('timeChips');",
  "  wrap.innerHTML = '';",
  "  times.forEach(function (t) { addTimeChip(t); });",
  "}",
  "function addTimeChip(value) {",
  "  var wrap = document.getElementById('timeChips');",
  "  var chip = document.createElement('span');",
  "  chip.className = 'time-chip';",
  "  var input = document.createElement('input');",
  "  input.type = 'text'; input.value = value; input.placeholder = 'HH:MM';",
  "  var removeBtn = document.createElement('button');",
  "  removeBtn.type = 'button'; removeBtn.textContent = '×';",
  "  removeBtn.addEventListener('click', function () { chip.remove(); });",
  "  chip.appendChild(input); chip.appendChild(removeBtn);",
  "  wrap.appendChild(chip);",
  "}",
  "function loadSettings() {",
  "  apiCall('/api/admin/settings').then(function (data) {",
  "    renderTimeChips(data.autoPublishTimes || []);",
  "  }).catch(function (err) { document.getElementById('settingsMsg').textContent = 'エラー: ' + err.message; });",
  "}",
  "function saveSettings() {",
  "  var inputs = document.querySelectorAll('#timeChips input');",
  "  var times = Array.prototype.map.call(inputs, function (i) { return i.value.trim(); }).filter(Boolean);",
  "  var msg = document.getElementById('settingsMsg');",
  "  msg.textContent = '保存中...';",
  "  apiCall('/api/admin/settings', 'PUT', { autoPublishTimes: times })",
  "    .then(function () { msg.textContent = '保存しました。最大10分で反映されます。'; })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- ニュース管理 ----",
  "function loadNewsAdmin() {",
  "  apiCall('/api/admin/news-list').then(function (data) {",
  "    var body = document.getElementById('newsAdminBody');",
  "    body.innerHTML = (data.news || []).map(function (n) {",
  "      return '<tr class=\"clickable\" onclick=\"openNewsEditor(' + n.id + ')\">' +",
  "        '<td>' + escapeHtml(n.title) + '</td><td>' + escapeHtml(n.category) + '</td>' +",
  "        '<td>' + escapeHtml(n.published_at) + '</td></tr>';",
  "    }).join('') || '<tr><td colspan=\"3\" class=\"sub\">ニュースがありません</td></tr>';",
  "  });",
  "}",
  "var editingNewsId = null;",
  "function openNewsEditor(id) {",
  "  editingNewsId = id;",
  "  apiCall('/api/admin/news/' + id).then(function (n) {",
  "    fillSelect(document.getElementById('newsEditCategory'), window.__NEWS_CATEGORIES__, n.category);",
  "    document.getElementById('newsEditTitle').value = n.title;",
  "    document.getElementById('newsEditBody').value = n.body;",
  "    document.getElementById('newsEditMsg').textContent = '';",
  "    document.getElementById('newsEditor').classList.remove('hidden');",
  "  });",
  "}",
  "function closeNewsEditor() {",
  "  editingNewsId = null;",
  "  document.getElementById('newsEditor').classList.add('hidden');",
  "}",
  "function saveNews() {",
  "  if (!editingNewsId) return;",
  "  var msg = document.getElementById('newsEditMsg');",
  "  msg.textContent = '保存中...';",
  "  apiCall('/api/admin/news/' + editingNewsId, 'PUT', {",
  "    title: document.getElementById('newsEditTitle').value,",
  "    body: document.getElementById('newsEditBody').value,",
  "    category: document.getElementById('newsEditCategory').value,",
  "  }).then(function () {",
  "    msg.textContent = '保存しました。';",
  "    loadNewsAdmin();",
  "    refresh();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 人物管理 ----",
  "function searchPeopleAdmin() {",
  "  var q = document.getElementById('peopleSearchAdmin').value.trim();",
  "  apiCall('/api/admin/people-list' + (q ? '?q=' + encodeURIComponent(q) : '')).then(function (data) {",
  "    var body = document.getElementById('peopleAdminBody');",
  "    body.innerHTML = (data.people || []).map(function (p) {",
  "      return '<tr class=\"clickable\" onclick=\"openPersonEditor(' + p.id + ')\">' +",
  "        '<td>' + escapeHtml(p.name) + '</td><td>' + escapeHtml(p.occupation || '') + '</td>' +",
  "        '<td>' + escapeHtml(p.status) + '</td></tr>';",
  "    }).join('') || '<tr><td colspan=\"3\" class=\"sub\">該当する人物がいません</td></tr>';",
  "  });",
  "}",
  "var editingPersonId = null;",
  "function openPersonEditor(id) {",
  "  editingPersonId = id;",
  "  apiCall('/api/admin/people/' + id).then(function (p) {",
  "    document.getElementById('personEditName').value = p.name || '';",
  "    document.getElementById('personEditKana').value = p.name_kana || '';",
  "    document.getElementById('personEditAge').value = p.age == null ? '' : p.age;",
  "    document.getElementById('personEditGender').value = p.gender || '';",
  "    document.getElementById('personEditOccupation').value = p.occupation || '';",
  "    document.getElementById('personEditMoney').value = p.money == null ? 0 : p.money;",
  "    document.getElementById('personEditBio').value = p.bio || '';",
  "    fillSelect(document.getElementById('personEditStatus'), window.__PERSON_STATUSES__, p.status);",
  "    var orgOptions = [{ value: '', label: '(所属なし)' }].concat(orgsCache.map(function (o) { return { value: o.id, label: o.name }; }));",
  "    fillSelect(document.getElementById('personEditOrg'), orgOptions, p.organization_id || '');",
  "    document.getElementById('personEditMsg').textContent = '';",
  "    document.getElementById('personEditor').classList.remove('hidden');",
  "  });",
  "}",
  "function closePersonEditor() {",
  "  editingPersonId = null;",
  "  document.getElementById('personEditor').classList.add('hidden');",
  "}",
  "function savePerson() {",
  "  if (!editingPersonId) return;",
  "  var msg = document.getElementById('personEditMsg');",
  "  msg.textContent = '保存中...';",
  "  var orgVal = document.getElementById('personEditOrg').value;",
  "  var ageVal = document.getElementById('personEditAge').value;",
  "  apiCall('/api/admin/people/' + editingPersonId, 'PUT', {",
  "    name: document.getElementById('personEditName').value,",
  "    name_kana: document.getElementById('personEditKana').value,",
  "    age: ageVal === '' ? null : Number(ageVal),",
  "    gender: document.getElementById('personEditGender').value,",
  "    occupation: document.getElementById('personEditOccupation').value,",
  "    organization_id: orgVal === '' ? null : Number(orgVal),",
  "    money: Number(document.getElementById('personEditMoney').value || 0),",
  "    status: document.getElementById('personEditStatus').value,",
  "    bio: document.getElementById('personEditBio').value,",
  "  }).then(function () {",
  "    msg.textContent = '保存しました。';",
  "    searchPeopleAdmin();",
  "  }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 経済コントロール ----",
  "function loadEconAdmin() {",
  "  apiCall('/api/admin/economy-list').then(function (data) {",
  "    orgsCache = data.organizations || [];",
  "    document.getElementById('priceIndexInput').value = data.priceIndex == null ? '' : data.priceIndex;",
  "    var body = document.getElementById('econAdminBody');",
  "    body.innerHTML = orgsCache.map(function (o) {",
  "      var detail = [o.industry, o.foundedYear ? (o.foundedYear + '年創業') : null, o.employeeScale]",
  "        .filter(Boolean).join(' / ');",
  "      var priceCell = o.kind === 'company'",
  "        ? '<div class=\"row\"><input type=\"number\" step=\"0.01\" style=\"width:6.5em\" value=\"' + (o.stockPrice == null ? '' : o.stockPrice) + '\" id=\"stock-' + o.id + '\" />' +",
  "          '<button class=\"secondary\" onclick=\"saveOrgStock(' + o.id + ')\">更新</button></div>'",
  "        : '<span class=\"sub\">-</span>';",
  "      return '<tr>' +",
  "        '<td>' + escapeHtml(o.name) + (detail ? '<div class=\"org-detail\">' + escapeHtml(detail) + '</div>' : '') + '</td>' +",
  "        '<td>' + escapeHtml(o.status) + '</td>' +",
  "        '<td>' + priceCell + '</td>' +",
  "        '<td><button class=\"secondary\" onclick=\"openOrgEditor(' + o.id + ')\">編集</button></td>' +",
  "        '</tr>';",
  "    }).join('') || '<tr><td colspan=\"4\" class=\"sub\">組織がありません</td></tr>';",
  "  });",
  "}",
  "function saveOrgStock(id) {",
  "  var input = document.getElementById('stock-' + id);",
  "  var value = Number(input.value);",
  "  var msg = document.getElementById('econMsg');",
  "  if (!value || value <= 0) { msg.textContent = '正の数値を入力してください。'; return; }",
  "  apiCall('/api/admin/economy/stock', 'POST', { organization_id: id, value: value })",
  "    .then(function () { msg.textContent = '株価を更新しました。'; loadEconAdmin(); })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "function savePriceIndex() {",
  "  var value = Number(document.getElementById('priceIndexInput').value);",
  "  var msg = document.getElementById('econMsg');",
  "  if (!value || value <= 0) { msg.textContent = '正の数値を入力してください。'; return; }",
  "  apiCall('/api/admin/economy/price-index', 'PUT', { value: value })",
  "    .then(function () { msg.textContent = '物価指数を更新しました。'; loadEconAdmin(); })",
  "    .catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "}",
  "",
  "// ---- 企業の追加・編集 ----",
  "var editingOrgId = null;",
  "function showOrgCreateForm() {",
  "  editingOrgId = null;",
  "  document.getElementById('orgEditorTitle').textContent = '新しい企業を追加';",
  "  document.getElementById('orgEditName').value = '';",
  "  document.getElementById('orgEditIndustry').value = '';",
  "  document.getElementById('orgEditEmployeeScale').value = '';",
  "  document.getElementById('orgEditFoundedYear').value = '';",
  "  document.getElementById('orgEditDescription').value = '';",
  "  fillSelect(document.getElementById('orgEditKind'), window.__ORG_KINDS__, 'company');",
  "  fillSelect(document.getElementById('orgEditStatus'), window.__ORG_STATUSES__, 'active');",
  "  document.getElementById('orgEditMsg').textContent = '';",
  "  document.getElementById('orgEditor').classList.remove('hidden');",
  "  document.getElementById('orgEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function openOrgEditor(id) {",
  "  var o = orgsCache.filter(function (x) { return x.id === id; })[0];",
  "  if (!o) return;",
  "  editingOrgId = id;",
  "  document.getElementById('orgEditorTitle').textContent = o.name + ' を編集';",
  "  document.getElementById('orgEditName').value = o.name || '';",
  "  document.getElementById('orgEditIndustry').value = o.industry || '';",
  "  document.getElementById('orgEditEmployeeScale').value = o.employeeScale || '';",
  "  document.getElementById('orgEditFoundedYear').value = o.foundedYear == null ? '' : o.foundedYear;",
  "  document.getElementById('orgEditDescription').value = o.description || '';",
  "  fillSelect(document.getElementById('orgEditKind'), window.__ORG_KINDS__, o.kind);",
  "  fillSelect(document.getElementById('orgEditStatus'), window.__ORG_STATUSES__, o.status);",
  "  document.getElementById('orgEditMsg').textContent = '';",
  "  document.getElementById('orgEditor').classList.remove('hidden');",
  "  document.getElementById('orgEditor').scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
  "}",
  "function closeOrgEditor() {",
  "  editingOrgId = null;",
  "  document.getElementById('orgEditor').classList.add('hidden');",
  "}",
  "function saveOrg() {",
  "  var msg = document.getElementById('orgEditMsg');",
  "  var fy = document.getElementById('orgEditFoundedYear').value;",
  "  var payload = {",
  "    name: document.getElementById('orgEditName').value,",
  "    kind: document.getElementById('orgEditKind').value,",
  "    industry: document.getElementById('orgEditIndustry').value,",
  "    employeeScale: document.getElementById('orgEditEmployeeScale').value,",
  "    foundedYear: fy === '' ? null : Number(fy),",
  "    description: document.getElementById('orgEditDescription').value,",
  "  };",
  "  msg.textContent = '保存中...';",
  "  if (editingOrgId) {",
  "    payload.status = document.getElementById('orgEditStatus').value;",
  "    apiCall('/api/admin/organizations/' + editingOrgId, 'PUT', payload).then(function (r) {",
  "      msg.textContent = r.clearedEmployees ? ('保存しました（倒産により' + r.clearedEmployees + '人が無所属になりました）') : '保存しました。';",
  "      loadEconAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  } else {",
  "    apiCall('/api/admin/organizations', 'POST', payload).then(function () {",
  "      msg.textContent = '新しい企業を追加しました。地図にも自動的に反映されます。';",
  "      loadEconAdmin();",
  "    }).catch(function (err) { msg.textContent = 'エラー: ' + err.message; });",
  "  }",
  "}",
  "",
  "(function init() {",
  "  var token = getToken();",
  "  if (token) {",
  "    refresh();",
  "    pollTimer = setInterval(refresh, 10000);",
  "  }",
  "})();",
].join("\n");
